/* eslint-disable @stylistic/padding-line-between-statements */
// AUTO-GENERATED. DO NOT EDIT.
// Regenerated by `pnpm run build` (genGlobal step).
//
// Re-declares every named ts-type-forge type as a global so consumers
// can opt-in to ambient access via
// `/// <reference types="ts-type-forge/global" />`.
// Importing the package by name (`import { X } from 'ts-type-forge'`)
// keeps named-only access without polluting the global namespace.

import type * as _TSTypeForge from './index.mjs';

declare global {
  type BigInt64 = _TSTypeForge.BigInt64;
  type BigUint64 = _TSTypeForge.BigUint64;
  type UnknownBrand = _TSTypeForge.UnknownBrand;
  type Brand<
    T,
    TrueKeys extends string,
    FalseKeys extends string = never,
  > = _TSTypeForge.Brand<T, TrueKeys, FalseKeys>;
  type UnwrapBrandTrueKeys<B extends UnknownBrand> =
    _TSTypeForge.UnwrapBrandTrueKeys<B>;
  type UnwrapBrandFalseKeys<B extends UnknownBrand> =
    _TSTypeForge.UnwrapBrandFalseKeys<B>;
  type UnwrapBrandBooleanKeys<B extends UnknownBrand> =
    _TSTypeForge.UnwrapBrandBooleanKeys<B>;
  type UnwrapBrandKeys<B extends UnknownBrand> =
    _TSTypeForge.UnwrapBrandKeys<B>;
  type GetBrandKeysPart<B extends UnknownBrand> =
    _TSTypeForge.GetBrandKeysPart<B>;
  type GetBrandValuePart<B extends UnknownBrand> =
    _TSTypeForge.GetBrandValuePart<B>;
  type ExtendBrand<
    B extends UnknownBrand,
    T extends string,
    F extends string = never,
  > = _TSTypeForge.ExtendBrand<B, T, F>;
  type ChangeBaseBrand<
    B extends UnknownBrand,
    T,
  > = _TSTypeForge.ChangeBaseBrand<B, T>;
  type IntersectBrand<
    B1 extends UnknownBrand,
    B2 extends UnknownBrand,
  > = _TSTypeForge.IntersectBrand<B1, B2>;
  type NormalizeBrandUnion<B extends UnknownBrand> =
    _TSTypeForge.NormalizeBrandUnion<B>;
  type NaNType = _TSTypeForge.NaNType;
  type ValidNumber = _TSTypeForge.ValidNumber;
  type NonZeroNumber = _TSTypeForge.NonZeroNumber;
  type NonNegativeNumber = _TSTypeForge.NonNegativeNumber;
  type PositiveNumber = _TSTypeForge.PositiveNumber;
  type NegativeNumber = _TSTypeForge.NegativeNumber;
  type FiniteNumber = _TSTypeForge.FiniteNumber;
  type InfiniteNumber = _TSTypeForge.InfiniteNumber;
  type POSITIVE_INFINITY = _TSTypeForge.POSITIVE_INFINITY;
  type NEGATIVE_INFINITY = _TSTypeForge.NEGATIVE_INFINITY;
  type NonNegativeFiniteNumber = _TSTypeForge.NonNegativeFiniteNumber;
  type PositiveFiniteNumber = _TSTypeForge.PositiveFiniteNumber;
  type NegativeFiniteNumber = _TSTypeForge.NegativeFiniteNumber;
  type NonZeroFiniteNumber = _TSTypeForge.NonZeroFiniteNumber;
  type Float32 = _TSTypeForge.Float32;
  type Float64 = _TSTypeForge.Float64;
  type Int = _TSTypeForge.Int;
  type NonZeroInt = _TSTypeForge.NonZeroInt;
  type NonNegativeInt = _TSTypeForge.NonNegativeInt;
  type Uint = _TSTypeForge.Uint;
  type PositiveInt = _TSTypeForge.PositiveInt;
  type NegativeInt = _TSTypeForge.NegativeInt;
  type IntWithSmallInt = _TSTypeForge.IntWithSmallInt;
  type NonZeroIntWithSmallInt = _TSTypeForge.NonZeroIntWithSmallInt;
  type NonNegativeIntWithSmallInt = _TSTypeForge.NonNegativeIntWithSmallInt;
  type UintWithSmallInt = _TSTypeForge.UintWithSmallInt;
  type PositiveIntWithSmallInt = _TSTypeForge.PositiveIntWithSmallInt;
  type NegativeIntWithSmallInt = _TSTypeForge.NegativeIntWithSmallInt;
  type Int16 = _TSTypeForge.Int16;
  type NonZeroInt16 = _TSTypeForge.NonZeroInt16;
  type NonNegativeInt16 = _TSTypeForge.NonNegativeInt16;
  type PositiveInt16 = _TSTypeForge.PositiveInt16;
  type NegativeInt16 = _TSTypeForge.NegativeInt16;
  type Int16WithSmallInt = _TSTypeForge.Int16WithSmallInt;
  type NonZeroInt16WithSmallInt = _TSTypeForge.NonZeroInt16WithSmallInt;
  type NonNegativeInt16WithSmallInt = _TSTypeForge.NonNegativeInt16WithSmallInt;
  type PositiveInt16WithSmallInt = _TSTypeForge.PositiveInt16WithSmallInt;
  type NegativeInt16WithSmallInt = _TSTypeForge.NegativeInt16WithSmallInt;
  type Int32 = _TSTypeForge.Int32;
  type NonZeroInt32 = _TSTypeForge.NonZeroInt32;
  type NonNegativeInt32 = _TSTypeForge.NonNegativeInt32;
  type PositiveInt32 = _TSTypeForge.PositiveInt32;
  type NegativeInt32 = _TSTypeForge.NegativeInt32;
  type Int32WithSmallInt = _TSTypeForge.Int32WithSmallInt;
  type NonZeroInt32WithSmallInt = _TSTypeForge.NonZeroInt32WithSmallInt;
  type NonNegativeInt32WithSmallInt = _TSTypeForge.NonNegativeInt32WithSmallInt;
  type PositiveInt32WithSmallInt = _TSTypeForge.PositiveInt32WithSmallInt;
  type NegativeInt32WithSmallInt = _TSTypeForge.NegativeInt32WithSmallInt;
  type SafeInt = _TSTypeForge.SafeInt;
  type NonZeroSafeInt = _TSTypeForge.NonZeroSafeInt;
  type SafeUint = _TSTypeForge.SafeUint;
  type PositiveSafeInt = _TSTypeForge.PositiveSafeInt;
  type NegativeSafeInt = _TSTypeForge.NegativeSafeInt;
  type NonNegativeSafeInt = _TSTypeForge.NonNegativeSafeInt;
  type SafeIntWithSmallInt = _TSTypeForge.SafeIntWithSmallInt;
  type NonZeroSafeIntWithSmallInt = _TSTypeForge.NonZeroSafeIntWithSmallInt;
  type NonNegativeSafeIntWithSmallInt =
    _TSTypeForge.NonNegativeSafeIntWithSmallInt;
  type SafeUintWithSmallInt = _TSTypeForge.SafeUintWithSmallInt;
  type PositiveSafeIntWithSmallInt = _TSTypeForge.PositiveSafeIntWithSmallInt;
  type NegativeSafeIntWithSmallInt = _TSTypeForge.NegativeSafeIntWithSmallInt;
  type SmallInt<
    T extends '!=0' | '' | '<=0' | '<0' | '>=0' | '>0' = '',
    MaxIndex extends number =
      _TSTypeForge.TSTypeForgeInternals_SmallIntIndexMax,
  > = _TSTypeForge.SmallInt<T, MaxIndex>;
  type SmallUint = _TSTypeForge.SmallUint;
  type WithSmallInt<
    N extends Int,
    MaxIndex extends number =
      _TSTypeForge.TSTypeForgeInternals_SmallIntIndexMax,
  > = _TSTypeForge.WithSmallInt<N, MaxIndex>;
  type ExcludeSmallInt<
    N extends IntWithSmallInt,
    MaxIndex extends number =
      _TSTypeForge.TSTypeForgeInternals_SmallIntIndexMax,
  > = _TSTypeForge.ExcludeSmallInt<N, MaxIndex>;
  type Uint16 = _TSTypeForge.Uint16;
  type PositiveUint16 = _TSTypeForge.PositiveUint16;
  type NonZeroUint16 = _TSTypeForge.NonZeroUint16;
  type Uint16WithSmallInt = _TSTypeForge.Uint16WithSmallInt;
  type PositiveUint16WithSmallInt = _TSTypeForge.PositiveUint16WithSmallInt;
  type NonZeroUint16WithSmallInt = _TSTypeForge.NonZeroUint16WithSmallInt;
  type Uint32 = _TSTypeForge.Uint32;
  type PositiveUint32 = _TSTypeForge.PositiveUint32;
  type NonZeroUint32 = _TSTypeForge.NonZeroUint32;
  type Uint32WithSmallInt = _TSTypeForge.Uint32WithSmallInt;
  type PositiveUint32WithSmallInt = _TSTypeForge.PositiveUint32WithSmallInt;
  type NonZeroUint32WithSmallInt = _TSTypeForge.NonZeroUint32WithSmallInt;
  type TypeEq<A, B> = _TSTypeForge.TypeEq<A, B>;
  type TypeExtends<A, B> = _TSTypeForge.TypeExtends<A, B>;
  type IsFixedLengthList<T extends readonly unknown[]> =
    _TSTypeForge.IsFixedLengthList<T>;
  type IsNotFixedLengthList<T extends readonly unknown[]> =
    _TSTypeForge.IsNotFixedLengthList<T>;
  type IsNever<T> = _TSTypeForge.IsNever<T>;
  type IsUnion<U> = _TSTypeForge.IsUnion<U>;
  type LowerAlphabet = _TSTypeForge.LowerAlphabet;
  type UpperAlphabet = _TSTypeForge.UpperAlphabet;
  type Alphabet = _TSTypeForge.Alphabet;
  type FalsyValue = _TSTypeForge.FalsyValue;
  type Uint8 = _TSTypeForge.Uint8;
  type Uint9 = _TSTypeForge.Uint9;
  type Uint10 = _TSTypeForge.Uint10;
  type Int8 = _TSTypeForge.Int8;
  type Int9 = _TSTypeForge.Int9;
  type Int10 = _TSTypeForge.Int10;
  type MonthEnum = _TSTypeForge.MonthEnum;
  type MonthIndexEnum = _TSTypeForge.MonthIndexEnum;
  type DateEnum = _TSTypeForge.DateEnum;
  type DayOfWeekIndex = _TSTypeForge.DayOfWeekIndex;
  type DayOfWeekName = _TSTypeForge.DayOfWeekName;
  type HoursEnum = _TSTypeForge.HoursEnum;
  type MinutesEnum = _TSTypeForge.MinutesEnum;
  type SecondsEnum = _TSTypeForge.SecondsEnum;
  type MillisecondsEnum = _TSTypeForge.MillisecondsEnum;
  type Sexagesimal = _TSTypeForge.Sexagesimal;
  type Percent = _TSTypeForge.Percent;
  type Primitive = _TSTypeForge.Primitive;
  type UnknownRecord = _TSTypeForge.UnknownRecord;
  type HTTPRequestMethod = _TSTypeForge.HTTPRequestMethod;
  type BivariantHack<F extends (...args: readonly never[]) => unknown> =
    _TSTypeForge.BivariantHack<F>;
  type BoolNot<A extends boolean> = _TSTypeForge.BoolNot<A>;
  type BoolAnd<A extends boolean, B extends boolean> = _TSTypeForge.BoolAnd<
    A,
    B
  >;
  type BoolOr<A extends boolean, B extends boolean> = _TSTypeForge.BoolOr<A, B>;
  type BoolEq<A extends boolean, B extends boolean> = _TSTypeForge.BoolEq<A, B>;
  type BoolNand<A extends boolean, B extends boolean> = _TSTypeForge.BoolNand<
    A,
    B
  >;
  type BoolNor<A extends boolean, B extends boolean> = _TSTypeForge.BoolNor<
    A,
    B
  >;
  type BoolNeq<A extends boolean, B extends boolean> = _TSTypeForge.BoolNeq<
    A,
    B
  >;
  type JsonPrimitive = _TSTypeForge.JsonPrimitive;
  type MutableJsonValue = _TSTypeForge.MutableJsonValue;
  type JsonValue = _TSTypeForge.JsonValue;
  type JsonObject = _TSTypeForge.JsonObject;
  type MutableJsonObject = _TSTypeForge.MutableJsonObject;
  type Mutable<T> = _TSTypeForge.Mutable<T>;
  type ToMutableMap<T extends ReadonlyMap<any, any>> =
    _TSTypeForge.ToMutableMap<T>;
  type ToMutableSet<T extends ReadonlySet<any>> = _TSTypeForge.ToMutableSet<T>;
  type MutableSet<K> = _TSTypeForge.MutableSet<K>;
  type MutableMap<K, V> = _TSTypeForge.MutableMap<K, V>;
  type ToString<A> = _TSTypeForge.ToString<A>;
  type ToNumber<S extends `${number}`> = _TSTypeForge.ToNumber<S>;
  type ValueOf<T> = _TSTypeForge.ValueOf<T>;
  type Length<T extends Readonly<{ length: number }>> = _TSTypeForge.Length<T>;
  type FunctionType<A, B> = _TSTypeForge.FunctionType<A, B>;
  type Fn<A, B> = _TSTypeForge.Fn<A, B>;
  type MonoTypeFunction<X> = _TSTypeForge.MonoTypeFunction<X>;
  type Reducer<S, A> = _TSTypeForge.Reducer<S, A>;
  type AnyFn = _TSTypeForge.AnyFn;
  type UnionToIntersection<T> = _TSTypeForge.UnionToIntersection<T>;
  type MergeIntersection<R extends UnknownRecord> =
    _TSTypeForge.MergeIntersection<R>;
  type ExcludeFalsyValue<A> = _TSTypeForge.ExcludeFalsyValue<A>;
  type Intersection<Types extends readonly unknown[]> =
    _TSTypeForge.Intersection<Types>;
  type WidenLiteral<T> = _TSTypeForge.WidenLiteral<T>;
  type DeepPick<T, Path extends readonly PropertyKey[]> = _TSTypeForge.DeepPick<
    T,
    Path
  >;
  type DeepOmit<T, Path extends readonly PropertyKey[]> = _TSTypeForge.DeepOmit<
    T,
    Path
  >;
  type DeepReadonly<T> = _TSTypeForge.DeepReadonly<T>;
  type DeepMutable<T> = _TSTypeForge.DeepMutable<T>;
  type DeepPartial<T> = _TSTypeForge.DeepPartial<T>;
  type DeepRequired<T> = _TSTypeForge.DeepRequired<T>;
  type PartiallyPartial<T, K extends keyof T> = _TSTypeForge.PartiallyPartial<
    T,
    K
  >;
  type PartiallyOptional<T, K extends keyof T> = _TSTypeForge.PartiallyOptional<
    T,
    K
  >;
  type PartiallyNullable<T, K extends keyof T> = _TSTypeForge.PartiallyNullable<
    T,
    K
  >;
  type PartiallyRequired<T, K extends keyof T> = _TSTypeForge.PartiallyRequired<
    T,
    K
  >;
  type PickUndefined<R extends UnknownRecord> = _TSTypeForge.PickUndefined<R>;
  type MapToNever<R extends UnknownRecord> = _TSTypeForge.MapToNever<R>;
  type OptionalKeys<R extends UnknownRecord> = _TSTypeForge.OptionalKeys<R>;
  type RequiredKeys<R extends UnknownRecord> = _TSTypeForge.RequiredKeys<R>;
  type RecordPathsWithIndex<R> = _TSTypeForge.RecordPathsWithIndex<R>;
  type RecordPaths<R> = _TSTypeForge.RecordPaths<R>;
  type RecordPathAndValueTypeTuple<R> =
    _TSTypeForge.RecordPathAndValueTypeTuple<R>;
  type RecordLeafPaths<R> = _TSTypeForge.RecordLeafPaths<R>;
  type RecordLeafPathsWithIndex<R> = _TSTypeForge.RecordLeafPathsWithIndex<R>;
  type RecordUpdated<
    R,
    Path extends RecordPaths<R>,
    ValueAfter,
  > = _TSTypeForge.RecordUpdated<R, Path, ValueAfter>;
  type RecordValueAtPath<
    R,
    Path extends RecordPaths<R>,
  > = _TSTypeForge.RecordValueAtPath<R, Path>;
  type RecordValueAtPathWithIndex<
    R,
    Path extends RecordPathsWithIndex<R>,
  > = _TSTypeForge.RecordValueAtPathWithIndex<R, Path>;
  type StrictExtract<T, U extends T> = _TSTypeForge.StrictExtract<T, U>;
  type RelaxedExtract<T, U> = _TSTypeForge.RelaxedExtract<T, U>;
  type StrictPick<T, K extends keyof T> = _TSTypeForge.StrictPick<T, K>;
  type RelaxedPick<T, K> = _TSTypeForge.RelaxedPick<T, K>;
  type StrictExclude<T, U extends T> = _TSTypeForge.StrictExclude<T, U>;
  type RelaxedExclude<T, U> = _TSTypeForge.RelaxedExclude<T, U>;
  type StrictOmit<T, K extends keyof T> = _TSTypeForge.StrictOmit<T, K>;
  type RelaxedOmit<T, K> = _TSTypeForge.RelaxedOmit<T, K>;
  type ReadonlyRecord<K extends PropertyKey, T> = _TSTypeForge.ReadonlyRecord<
    K,
    T
  >;
  type MutableRecord<K extends PropertyKey, T> = _TSTypeForge.MutableRecord<
    K,
    T
  >;
  type MutableNonEmptyArray<A> = _TSTypeForge.MutableNonEmptyArray<A>;
  type NonEmptyArray<A> = _TSTypeForge.NonEmptyArray<A>;
  type ArrayElement<S> = _TSTypeForge.ArrayElement<S>;
  type ArrayOfLength<N extends number, Elm> = _TSTypeForge.ArrayOfLength<
    N,
    Elm
  >;
  type MutableArrayOfLength<
    N extends number,
    Elm,
  > = _TSTypeForge.MutableArrayOfLength<N, Elm>;
  type MutableArrayAtLeastLen<
    N extends number,
    Elm,
  > = _TSTypeForge.MutableArrayAtLeastLen<N, Elm>;
  type ArrayAtLeastLen<N extends number, Elm> = _TSTypeForge.ArrayAtLeastLen<
    N,
    Elm
  >;
  type ArrayBoundedLen<
    Min extends number,
    Max extends number,
    Elm,
  > = _TSTypeForge.ArrayBoundedLen<Min, Max, Elm>;
  type MutableArrayBoundedLen<
    Min extends number,
    Max extends number,
    Elm,
  > = _TSTypeForge.MutableArrayBoundedLen<Min, Max, Elm>;
  type ArrayAtMostLen<N extends number, Elm> = _TSTypeForge.ArrayAtMostLen<
    N,
    Elm
  >;
  type MutableArrayAtMostLen<
    N extends number,
    Elm,
  > = _TSTypeForge.MutableArrayAtMostLen<N, Elm>;
  type IndexOfTuple<T extends readonly unknown[]> =
    _TSTypeForge.IndexOfTuple<T>;
  type NegativeIndexOfTuple<T extends readonly unknown[]> =
    _TSTypeForge.NegativeIndexOfTuple<T>;
  type MakeTuple<Elm, N extends number> = _TSTypeForge.MakeTuple<Elm, N>;
  type AbsoluteValue<N extends number> = _TSTypeForge.AbsoluteValue<N>;
  type Abs<N extends number> = _TSTypeForge.Abs<N>;
  type Increment<N extends number> = _TSTypeForge.Increment<N>;
  type Decrement<N extends number> = _TSTypeForge.Decrement<N>;
  type Index<N extends number> = _TSTypeForge.Index<N>;
  type IndexInclusive<N extends number> = _TSTypeForge.IndexInclusive<N>;
  type NegativeIndex<N extends number> = _TSTypeForge.NegativeIndex<N>;
  type Max<N extends Uint10> = _TSTypeForge.Max<N>;
  type Min<N extends Uint10> = _TSTypeForge.Min<N>;
  type Seq<N extends number> = _TSTypeForge.Seq<N>;
  type UintRange<
    Start extends number,
    End extends number,
  > = _TSTypeForge.UintRange<Start, End>;
  type UintRangeInclusive<
    MinValue extends number,
    MaxValue extends number,
  > = _TSTypeForge.UintRangeInclusive<MinValue, MaxValue>;
  namespace List {
    export type Head<
      T extends readonly unknown[],
      D = never,
    > = _TSTypeForge.List.Head<T, D>;
    export type Last<T extends readonly unknown[]> = _TSTypeForge.List.Last<T>;
    export type ButLast<A extends readonly unknown[]> =
      _TSTypeForge.List.ButLast<A>;
    export type Tail<A extends readonly unknown[]> = _TSTypeForge.List.Tail<A>;
    export type Reverse<L extends readonly unknown[]> =
      _TSTypeForge.List.Reverse<L>;
    export type Take<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.List.Take<N, T>;
    export type Skip<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.List.Skip<N, T>;
    export type TakeLast<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.List.TakeLast<N, T>;
    export type SkipLast<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.List.SkipLast<N, T>;
    export type SetAt<
      T extends readonly unknown[],
      I extends number,
      V,
    > = _TSTypeForge.List.SetAt<T, I, V>;
    export type Flatten<T extends readonly (readonly unknown[])[]> =
      _TSTypeForge.List.Flatten<T>;
    export type Concat<
      A extends readonly unknown[],
      B extends readonly unknown[],
    > = _TSTypeForge.List.Concat<A, B>;
    export type Zip<
      A extends readonly unknown[],
      B extends readonly unknown[],
    > = _TSTypeForge.List.Zip<A, B>;
    export type Partition<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.List.Partition<N, T>;
  }
  namespace Tuple {
    export type Head<
      T extends readonly unknown[],
      D = never,
    > = _TSTypeForge.Tuple.Head<T, D>;
    export type Last<T extends readonly unknown[]> = _TSTypeForge.Tuple.Last<T>;
    export type ButLast<A extends readonly unknown[]> =
      _TSTypeForge.Tuple.ButLast<A>;
    export type Tail<A extends readonly unknown[]> = _TSTypeForge.Tuple.Tail<A>;
    export type Reverse<L extends readonly unknown[]> =
      _TSTypeForge.Tuple.Reverse<L>;
    export type Take<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.Tuple.Take<N, T>;
    export type Skip<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.Tuple.Skip<N, T>;
    export type TakeLast<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.Tuple.TakeLast<N, T>;
    export type SkipLast<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.Tuple.SkipLast<N, T>;
    export type SetAt<
      T extends readonly unknown[],
      I extends number,
      V,
    > = _TSTypeForge.Tuple.SetAt<T, I, V>;
    export type Flatten<T extends readonly (readonly unknown[])[]> =
      _TSTypeForge.Tuple.Flatten<T>;
    export type Concat<
      A extends readonly unknown[],
      B extends readonly unknown[],
    > = _TSTypeForge.Tuple.Concat<A, B>;
    export type Zip<
      A extends readonly unknown[],
      B extends readonly unknown[],
    > = _TSTypeForge.Tuple.Zip<A, B>;
    export type Partition<
      N extends number,
      T extends readonly unknown[],
    > = _TSTypeForge.Tuple.Partition<N, T>;
  }
}
