// this is done for convenience - saves migrating all of the old rules
export {
  AnyType,
  containsAllTypesByName,
  getConstrainedTypeAtLocation,
  getContextualType,
  getDeclaration,
  getSourceFileOfNode,
  getTokenAtPosition,
  getTypeArguments,
  getTypeFlags,
  getTypeName,
  getTypeOfPropertyOfName,
  getTypeOfPropertyOfType,
  isAnyOrAnyArrayTypeDiscriminated,
  isNullableType,
  isTypeAnyArrayType,
  isTypeAnyType,
  isTypeArrayTypeOrUnionOfArrayTypes,
  isTypeBigIntLiteralType,
  isTypeFlagSet,
  isTypeNeverType,
  // isTypeReadonly,
  isTypeReferenceType,
  isTypeTemplateLiteralType,
  isTypeUnknownArrayType,
  isTypeUnknownType,
  isUnsafeAssignment,
  // ReadonlynessOptions,
  // readonlynessOptionsDefaults,
  // readonlynessOptionsSchema,
  requiresQuoting,
  typeIsOrHasBaseType,
} from '@typescript-eslint/type-utils';
export * from './isTypeReadonly';
