type SourceFileMapping = Readonly<{
  sourcePath: string;
  sampleFiles: readonly string[];
}>;

/**
 * Mapping from source files to their sample code files. Sample files should be
 * listed in the order they appear in the source file's JSDoc.
 *
 * HOW TO USE:
 *
 * 1. In the source file JSDoc, add @example blocks:
 *
 * @example
 * ```ts
 * ```
 *
 * 2. Add the source file path and its sample files to this mapping in the order
 *   they appear in the source file (top to bottom).
 *
 * 3. Run: pnpm run doc:embed-jsdoc (or pnpm exec tsx scripts/cmd/embed-jsdoc-examples.mts)
 *
 * The script will replace each ```ts block sequentially with the corresponding sample code.
 */
export const sourceFileMappings: readonly SourceFileMapping[] = [
  {
    sourcePath: 'src/array/impl/array-utils-creation.mts',
    sampleFiles: [
      'samples/src/array/array-utils/zeros-example.mts',
      'samples/src/array/array-utils/seq-example.mts',
      'samples/src/array/array-utils/create-example.mts',
      'samples/src/array/array-utils/generate-example.mts',
      'samples/src/array/array-utils/generate-async-example.mts',
      'samples/src/array/array-utils/copy-example.mts',
      'samples/src/array/array-utils/range-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-size.mts',
    sampleFiles: ['samples/src/array/array-utils/size-example.mts'],
  },
  {
    sourcePath: 'src/array/impl/array-utils-element-access.mts',
    sampleFiles: [
      'samples/src/array/array-utils/at-example.mts',
      'samples/src/array/array-utils/head-example.mts',
      'samples/src/array/array-utils/last-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-validation.mts',
    sampleFiles: [
      'samples/src/array/array-utils/is-array-example.mts',
      'samples/src/array/array-utils/is-empty-example.mts',
      'samples/src/array/array-utils/is-non-empty-example.mts',
      'samples/src/array/array-utils/is-array-of-length-example.mts',
      'samples/src/array/array-utils/is-array-at-least-length-example.mts',
      'samples/src/array/array-utils/every-example.mts',
      'samples/src/array/array-utils/some-example.mts',
      'samples/src/array/array-utils/index-is-in-range-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-iterators.mts',
    sampleFiles: [
      'samples/src/array/array-utils/entries-example.mts',
      'samples/src/array/array-utils/values-example.mts',
      'samples/src/array/array-utils/indices-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-modification.mts',
    sampleFiles: [
      'samples/src/array/array-utils/set-example.mts',
      'samples/src/array/array-utils/to-updated-example.mts',
      'samples/src/array/array-utils/to-inserted-example.mts',
      'samples/src/array/array-utils/to-removed-example.mts',
      'samples/src/array/array-utils/to-pushed-example.mts',
      'samples/src/array/array-utils/to-unshifted-example.mts',
      'samples/src/array/array-utils/to-filled-example.mts',
      'samples/src/array/array-utils/to-range-filled-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-slicing.mts',
    sampleFiles: [
      'samples/src/array/array-utils/tail-example.mts',
      'samples/src/array/array-utils/but-last-example.mts',
      'samples/src/array/array-utils/take-example.mts',
      'samples/src/array/array-utils/take-last-example.mts',
      'samples/src/array/array-utils/skip-example.mts',
      'samples/src/array/array-utils/skip-last-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-slice-clamped.mts',
    sampleFiles: ['samples/src/array/array-utils/slice-clamped-example.mts'],
  },
  {
    sourcePath: 'src/array/impl/array-utils-search.mts',
    sampleFiles: [
      'samples/src/array/array-utils/find-example.mts',
      'samples/src/array/array-utils/find-last-example.mts',
      'samples/src/array/array-utils/find-index-example.mts',
      'samples/src/array/array-utils/find-last-index-example.mts',
      'samples/src/array/array-utils/index-of-example.mts',
      'samples/src/array/array-utils/index-of-from-example.mts',
      'samples/src/array/array-utils/last-index-of-example.mts',
      'samples/src/array/array-utils/last-index-of-from-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-reducing-value.mts',
    sampleFiles: [
      'samples/src/array/array-utils/min-example.mts',
      'samples/src/array/array-utils/max-example.mts',
      'samples/src/array/array-utils/min-by-example.mts',
      'samples/src/array/array-utils/max-by-example.mts',
      'samples/src/array/array-utils/count-example.mts',
      'samples/src/array/array-utils/count-by-example.mts',
      'samples/src/array/array-utils/foldl-example.mts',
      'samples/src/array/array-utils/foldr-example.mts',
      'samples/src/array/array-utils/sum-example.mts',
      'samples/src/array/array-utils/join-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-transformation.mts',
    sampleFiles: [
      'samples/src/array/array-utils/map-example.mts',
      'samples/src/array/array-utils/scan-example.mts',
      'samples/src/array/array-utils/to-reversed-example.mts',
      'samples/src/array/array-utils/to-sorted-example.mts',
      'samples/src/array/array-utils/to-sorted-by-example.mts',
      'samples/src/array/array-utils/filter-example.mts',
      'samples/src/array/array-utils/filter-not-example.mts',
      'samples/src/array/array-utils/uniq-example.mts',
      'samples/src/array/array-utils/uniq-by-example.mts',
      'samples/src/array/array-utils/flat-example.mts',
      'samples/src/array/array-utils/flat-map-example.mts',
      'samples/src/array/array-utils/partition-example.mts',
      'samples/src/array/array-utils/concat-example.mts',
      'samples/src/array/array-utils/group-by-example.mts',
      'samples/src/array/array-utils/zip-example.mts',
    ],
  },
  {
    sourcePath: 'src/array/impl/array-utils-set-op.mts',
    sampleFiles: [
      'samples/src/array/array-utils/eq-example.mts',
      'samples/src/array/array-utils/is-subset-example.mts',
      'samples/src/array/array-utils/is-superset-example.mts',
      'samples/src/array/array-utils/set-intersection-example.mts',
      'samples/src/array/array-utils/set-difference-example.mts',
      'samples/src/array/array-utils/sorted-num-set-difference-example.mts',
    ],
  },
  {
    sourcePath: 'src/collections/imap.mts',
    sampleFiles: [
      'samples/src/collections/imap/size-example.mts',
      'samples/src/collections/imap/has-example.mts',
      'samples/src/collections/imap/get-example.mts',
      'samples/src/collections/imap/every-example.mts',
      'samples/src/collections/imap/some-example.mts',
      'samples/src/collections/imap/delete-example.mts',
      'samples/src/collections/imap/set-example.mts',
      'samples/src/collections/imap/update-example.mts',
      'samples/src/collections/imap/with-mutations-example.mts',
      'samples/src/collections/imap/map-example.mts',
      'samples/src/collections/imap/map-keys-example.mts',
      'samples/src/collections/imap/map-entries-example.mts',
      'samples/src/collections/imap/for-each-example.mts',
      'samples/src/collections/imap/keys-method-example.mts',
      'samples/src/collections/imap/values-method-example.mts',
      'samples/src/collections/imap/entries-method-example.mts',
      'samples/src/collections/imap/to-keys-array-example.mts',
      'samples/src/collections/imap/to-values-array-example.mts',
      'samples/src/collections/imap/to-entries-array-example.mts',
      'samples/src/collections/imap/to-array-example.mts',
      'samples/src/collections/imap/to-raw-map-example.mts',
      'samples/src/collections/imap/create-example.mts',
      'samples/src/collections/imap/equal-example.mts',
      'samples/src/collections/imap/iterator-example.mts',
    ],
  },
  {
    sourcePath: 'src/collections/iset-mapped.mts',
    sampleFiles: [
      'samples/src/collections/iset-mapped/size-example.mts',
      'samples/src/collections/iset-mapped/is-empty-example.mts',
      'samples/src/collections/iset-mapped/has-example.mts',
      'samples/src/collections/iset-mapped/every-example.mts',
      'samples/src/collections/iset-mapped/some-example.mts',
      'samples/src/collections/iset-mapped/add-example.mts',
      'samples/src/collections/iset-mapped/delete-example.mts',
      'samples/src/collections/iset-mapped/with-mutations-example.mts',
      'samples/src/collections/iset-mapped/map-example.mts',
      'samples/src/collections/iset-mapped/filter-example.mts',
      'samples/src/collections/iset-mapped/filter-not-example.mts',
      'samples/src/collections/iset-mapped/for-each-example.mts',
      'samples/src/collections/iset-mapped/is-subset-of-example.mts',
      'samples/src/collections/iset-mapped/is-superset-of-example.mts',
      'samples/src/collections/iset-mapped/subtract-example.mts',
      'samples/src/collections/iset-mapped/intersect-example.mts',
      'samples/src/collections/iset-mapped/union-example.mts',
      'samples/src/collections/iset-mapped/keys-example.mts',
      'samples/src/collections/iset-mapped/values-example.mts',
      'samples/src/collections/iset-mapped/entries-example.mts',
      'samples/src/collections/iset-mapped/to-array-example.mts',
      'samples/src/collections/iset-mapped/to-raw-set-example.mts',
      'samples/src/collections/iset-mapped/create-example.mts',
      'samples/src/collections/iset-mapped/equal-example.mts',
      'samples/src/collections/iset-mapped/diff-example.mts',
      'samples/src/collections/iset-mapped/intersection-function-example.mts',
      'samples/src/collections/iset-mapped/union-function-example.mts',
      'samples/src/collections/iset-mapped/iterator-example.mts',
    ],
  },
  {
    sourcePath: 'src/collections/iset.mts',
    sampleFiles: [
      'samples/src/collections/iset/size-example.mts',
      'samples/src/collections/iset/is-empty-example.mts',
      'samples/src/collections/iset/has-example.mts',
      'samples/src/collections/iset/every-example.mts',
      'samples/src/collections/iset/some-example.mts',
      'samples/src/collections/iset/add-example.mts',
      'samples/src/collections/iset/delete-example.mts',
      'samples/src/collections/iset/with-mutations-example.mts',
      'samples/src/collections/iset/map-example.mts',
      'samples/src/collections/iset/filter-example.mts',
      'samples/src/collections/iset/filter-not-example.mts',
      'samples/src/collections/iset/is-subset-of-example.mts',
      'samples/src/collections/iset/is-superset-of-example.mts',
      'samples/src/collections/iset/subtract-example.mts',
      'samples/src/collections/iset/intersect-example.mts',
      'samples/src/collections/iset/union-example.mts',
      'samples/src/collections/iset/for-each-example.mts',
      'samples/src/collections/iset/keys-example.mts',
      'samples/src/collections/iset/values-example.mts',
      'samples/src/collections/iset/entries-example.mts',
      'samples/src/collections/iset/to-array-example.mts',
      'samples/src/collections/iset/to-raw-set-example.mts',
      'samples/src/collections/iset/create-example.mts',
      'samples/src/collections/iset/equal-example.mts',
      'samples/src/collections/iset/diff-example.mts',
      'samples/src/collections/iset/intersection-function-example.mts',
      'samples/src/collections/iset/union-function-example.mts',
      'samples/src/collections/iset/iterator-example.mts',
    ],
  },
  {
    sourcePath: 'src/collections/queue.mts',
    sampleFiles: [
      'samples/src/collections/queue/create-queue-example.mts',
      'samples/src/collections/queue/create-queue-example.mts',
      'samples/src/collections/queue/create-queue-example.mts',
      'samples/src/collections/queue/create-queue-example.mts',
      'samples/src/collections/queue/create-queue-example.mts',
    ],
  },
  {
    sourcePath: 'src/collections/stack.mts',
    sampleFiles: [
      'samples/src/collections/stack/create-stack-example.mts',
      'samples/src/collections/stack/create-stack-example.mts',
      'samples/src/collections/stack/create-stack-example.mts',
      'samples/src/collections/stack/create-stack-example.mts',
      'samples/src/collections/stack/create-stack-example.mts',
    ],
  },
  {
    sourcePath: 'src/functional/match.mts',
    sampleFiles: ['samples/src/functional/match/match-exhaustive-example.mts'],
  },
  {
    sourcePath: 'src/functional/optional.mts',
    sampleFiles: [
      'samples/src/functional/optional/is-optional-example.mts',
      'samples/src/functional/optional/some-example.mts',
      'samples/src/functional/optional/some-example.mts',
      'samples/src/functional/optional/is-some-example.mts',
      'samples/src/functional/optional/is-none-example.mts',
      'samples/src/functional/optional/unwrap-throw-example.mts',
      'samples/src/functional/optional/unwrap-example.mts',
      'samples/src/functional/optional/unwrap-or-example.mts',
      'samples/src/functional/optional/or-else-example.mts',
      'samples/src/functional/optional/map-example.mts',
      'samples/src/functional/optional/flat-map-example.mts',
      'samples/src/functional/optional/filter-example.mts',
      'samples/src/functional/optional/expect-to-be-example.mts',
      'samples/src/functional/optional/zip-example.mts',
      'samples/src/functional/optional/from-nullable-example.mts',
      'samples/src/functional/optional/to-nullable-example.mts',
    ],
  },
  {
    sourcePath: 'src/functional/pipe.mts',
    sampleFiles: [
      'samples/src/functional/pipe/pipe-map-example.mts',
      'samples/src/functional/pipe/pipe-map-nullable-example.mts',
      'samples/src/functional/pipe/pipe-map-optional-example.mts',
    ],
  },
  {
    sourcePath: 'src/functional/result.mts',
    sampleFiles: [
      'samples/src/functional/result/is-result-example.mts',
      'samples/src/functional/result/ok-err-example.mts',
      'samples/src/functional/result/ok-err-example.mts',
      'samples/src/functional/result/is-ok-example.mts',
      'samples/src/functional/result/is-ok-example.mts',
      'samples/src/functional/result/unwrap-throw-example.mts',
      'samples/src/functional/result/unwrap-ok-example.mts',
      'samples/src/functional/result/unwrap-ok-or-example.mts',
      'samples/src/functional/result/unwrap-err-throw-example.mts',
      'samples/src/functional/result/unwrap-err-example.mts',
      'samples/src/functional/result/unwrap-err-or-example.mts',
      'samples/src/functional/result/map-example.mts',
      'samples/src/functional/result/map-err-example.mts',
      'samples/src/functional/result/fold-example.mts',
      'samples/src/functional/result/flat-map-example.mts',
      'samples/src/functional/result/expect-to-be-example.mts',
      'samples/src/functional/result/from-promise-example.mts',
      'samples/src/functional/result/from-throwable-example.mts',
      'samples/src/functional/result/swap-example.mts',
      'samples/src/functional/result/to-optional-example.mts',
      'samples/src/functional/result/or-else-example.mts',
      'samples/src/functional/result/zip-example.mts',
    ],
  },
  {
    sourcePath: 'src/guard/has-key.mts',
    sampleFiles: ['samples/src/guard/has-key/has-key-example.mts'],
  },
  {
    sourcePath: 'src/guard/is-non-empty-string.mts',
    sampleFiles: [
      'samples/src/guard/is-non-empty-string/is-non-empty-string-example.mts',
    ],
  },
  {
    sourcePath: 'src/guard/is-non-null-object.mts',
    sampleFiles: [
      'samples/src/guard/is-non-null-object/is-non-null-object-example.mts',
    ],
  },
  {
    sourcePath: 'src/guard/is-primitive.mts',
    sampleFiles: ['samples/src/guard/is-primitive/is-primitive-example.mts'],
  },
  {
    sourcePath: 'src/guard/is-record.mts',
    sampleFiles: ['samples/src/guard/is-record/is-record-example.mts'],
  },
  {
    sourcePath: 'src/guard/is-type.mts',
    sampleFiles: [
      'samples/src/guard/is-type/is-undefined-example.mts',
      'samples/src/guard/is-type/is-not-undefined-example.mts',
      'samples/src/guard/is-type/is-boolean-example.mts',
      'samples/src/guard/is-type/is-not-boolean-example.mts',
      'samples/src/guard/is-type/is-number-example.mts',
      'samples/src/guard/is-type/is-not-number-example.mts',
      'samples/src/guard/is-type/is-bigint-example.mts',
      'samples/src/guard/is-type/is-not-bigint-example.mts',
      'samples/src/guard/is-type/is-string-example.mts',
      'samples/src/guard/is-type/is-not-string-example.mts',
      'samples/src/guard/is-type/is-symbol-example.mts',
      'samples/src/guard/is-type/is-not-symbol-example.mts',
      'samples/src/guard/is-type/is-null-example.mts',
      'samples/src/guard/is-type/is-not-null-example.mts',
      'samples/src/guard/is-type/is-nullish-example.mts',
      'samples/src/guard/is-type/is-non-nullish-example.mts',
    ],
  },
  {
    sourcePath: 'src/guard/key-is-in.mts',
    sampleFiles: ['samples/src/guard/key-is-in/key-is-in-example.mts'],
  },
  {
    sourcePath: 'src/iterator/range.mts',
    sampleFiles: ['samples/src/iterator/range-example.mts'],
  },
  {
    sourcePath: 'src/number/branded-types/int.mts',
    sampleFiles: [
      'samples/src/number/branded-types/int/is-int-example.mts',
      'samples/src/number/branded-types/int/as-int-example.mts',
      'samples/src/number/branded-types/int/is-int-example.mts',
      'samples/src/number/branded-types/int/abs-example.mts',
      'samples/src/number/branded-types/int/min-example.mts',
      'samples/src/number/branded-types/int/max-example.mts',
      'samples/src/number/branded-types/int/random-example.mts',
      'samples/src/number/branded-types/int/pow-example.mts',
      'samples/src/number/branded-types/int/add-example.mts',
      'samples/src/number/branded-types/int/sub-example.mts',
      'samples/src/number/branded-types/int/mul-example.mts',
      'samples/src/number/branded-types/int/div-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/branded-types/positive-int.mts',
    sampleFiles: [
      'samples/src/number/branded-types/positive-int/is-positive-int-example.mts',
      'samples/src/number/branded-types/positive-int/as-positive-int-example.mts',
      'samples/src/number/branded-types/positive-int/is-positive-int-example.mts',
      'samples/src/number/branded-types/positive-int/min-example.mts',
      'samples/src/number/branded-types/positive-int/max-example.mts',
      'samples/src/number/branded-types/positive-int/clamp-example.mts',
      'samples/src/number/branded-types/positive-int/random-example.mts',
      'samples/src/number/branded-types/positive-int/pow-example.mts',
      'samples/src/number/branded-types/positive-int/add-example.mts',
      'samples/src/number/branded-types/positive-int/sub-example.mts',
      'samples/src/number/branded-types/positive-int/mul-example.mts',
      'samples/src/number/branded-types/positive-int/div-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/branded-types/positive-safe-int.mts',
    sampleFiles: [
      'samples/src/number/branded-types/positive-safe-int/is-positive-safe-int-example.mts',
      'samples/src/number/branded-types/positive-safe-int/as-positive-safe-int-example.mts',
      'samples/src/number/branded-types/positive-safe-int/is-positive-safe-int-example.mts',
      'samples/src/number/branded-types/positive-safe-int/min-example.mts',
      'samples/src/number/branded-types/positive-safe-int/max-example.mts',
      'samples/src/number/branded-types/positive-safe-int/clamp-example.mts',
      'samples/src/number/branded-types/positive-safe-int/random-example.mts',
      'samples/src/number/branded-types/positive-safe-int/pow-example.mts',
      'samples/src/number/branded-types/positive-safe-int/add-example.mts',
      'samples/src/number/branded-types/positive-safe-int/sub-example.mts',
      'samples/src/number/branded-types/positive-safe-int/mul-example.mts',
      'samples/src/number/branded-types/positive-safe-int/div-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/branded-types/safe-int.mts',
    sampleFiles: [
      'samples/src/number/branded-types/safe-int/is-safe-int-example.mts',
      'samples/src/number/branded-types/safe-int/as-safe-int-example.mts',
      'samples/src/number/branded-types/safe-int/is-safe-int-example.mts',
      'samples/src/number/branded-types/safe-int/abs-example.mts',
      'samples/src/number/branded-types/safe-int/min-example.mts',
      'samples/src/number/branded-types/safe-int/max-example.mts',
      'samples/src/number/branded-types/safe-int/clamp-example.mts',
      'samples/src/number/branded-types/safe-int/random-example.mts',
      'samples/src/number/branded-types/safe-int/pow-example.mts',
      'samples/src/number/branded-types/safe-int/add-example.mts',
      'samples/src/number/branded-types/safe-int/sub-example.mts',
      'samples/src/number/branded-types/safe-int/mul-example.mts',
      'samples/src/number/branded-types/safe-int/div-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/branded-types/uint.mts',
    sampleFiles: [
      'samples/src/number/branded-types/uint/is-uint-example.mts',
      'samples/src/number/branded-types/uint/as-uint-example.mts',
      'samples/src/number/branded-types/uint/is-uint-example.mts',
      'samples/src/number/branded-types/uint/min-example.mts',
      'samples/src/number/branded-types/uint/max-example.mts',
      'samples/src/number/branded-types/uint/clamp-example.mts',
      'samples/src/number/branded-types/uint/random-example.mts',
      'samples/src/number/branded-types/uint/pow-example.mts',
      'samples/src/number/branded-types/uint/add-example.mts',
      'samples/src/number/branded-types/uint/sub-example.mts',
      'samples/src/number/branded-types/uint/mul-example.mts',
      'samples/src/number/branded-types/uint/div-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/num.mts',
    sampleFiles: [
      'samples/src/number/num-from-example.mts',
      'samples/src/number/num-is-non-zero-example.mts',
      'samples/src/number/num-is-non-negative-example.mts',
      'samples/src/number/num-is-positive-example.mts',
      'samples/src/number/num-is-in-range-example.mts',
      'samples/src/number/num-is-in-range-inclusive-example.mts',
      'samples/src/number/num-is-uint-in-range-example.mts',
      'samples/src/number/num-is-uint-in-range-inclusive-example.mts',
      'samples/src/number/num-clamp-example.mts',
    ],
  },
  {
    sourcePath: 'src/number/refined-number-utils.mts',
    sampleFiles: [
      'samples/src/number/refined-number-utils/operators-for-integer-example.mts',
      'samples/src/number/refined-number-utils/operators-for-float-example.mts',
    ],
  },
  {
    sourcePath: 'src/json/json.mts',
    sampleFiles: [
      'samples/src/json/parse-example.mts',
      'samples/src/json/stringify-example.mts',
      'samples/src/json/stringify-selected-example.mts',
      'samples/src/json/stringify-sorted-key-example.mts',
    ],
  },
  {
    sourcePath: 'src/object/object.mts',
    sampleFiles: [
      'samples/src/object/shallow-eq-example.mts',
      'samples/src/object/pick-example.mts',
      'samples/src/object/omit-example.mts',
      'samples/src/object/from-entries-example.mts',
    ],
  },
  {
    sourcePath: 'src/promise/promise.mts',
    sampleFiles: ['samples/src/promise/create-promise-example.mts'],
  },
  {
    sourcePath: 'src/others/tuple.mts',
    sampleFiles: ['samples/src/others/tp-example.mts'],
  },
] as const;
