/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type TSESLint } from '@typescript-eslint/utils';
import { type Linter } from 'eslint';
import { expectType } from 'ts-data-forge';
import { type tsDataForgeRules } from './rules/index.mjs';

type SpreadOptionsIfIsArray<
  T extends readonly [Linter.StringSeverity, unknown],
> = T[1] extends readonly unknown[]
  ? readonly [Linter.StringSeverity, ...T[1]]
  : T;

/**
 * Extracts the options tuple type of a rule from its TypeScript
 * implementation, so that option types stay in sync with the rule source
 * without converting `meta.schema` (JSON Schema) back into TypeScript types.
 */
type RuleOptionsOf<Name extends keyof typeof tsDataForgeRules> =
  (typeof tsDataForgeRules)[Name] extends TSESLint.RuleModule<
    infer _MessageIds extends string,
    infer Options extends readonly unknown[]
  >
    ? Options
    : never;

/**
 * @description Unify non-mutating array element addition/removal patterns (`slice` / `toSpliced` / `filter` / `concat` / spread) into the corresponding ts-data-forge functions: `Arr.tail`, `Arr.skip`, `Arr.take`, `Arr.butLast`, `Arr.skipLast`, `Arr.takeLast`, `Arr.toUnshifted`, `Arr.toPushed`.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferCanonicalArraySlicing {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Normalize array-length checks to their canonical `Arr` guard: `xs.length <op> n` becomes the matching `Arr.is*` guard, and a degenerate guard becomes the named one for its family (`Arr.isFixedLengthArray(0, xs)` → `Arr.isEmpty`, `Arr.isFixedLengthTuple(0, xs)` → `Arr.isEmptyTuple`).
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferCanonicalLengthGuard {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Normalize an `Arr` length cast whose bounds are degenerate (e.g. `Arr.asMinLengthArray(1, xs)`, `Arr.asFixedLengthTuple(0, xs)`) to the cast that names that constraint directly, staying within the branded `*Array` or structural `*Tuple` family.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferCanonicalLengthCast {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `Array.isArray` with `Arr.isArray` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferArrIsArray {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `xs.reduce((a, b) => a + b, 0)` with `Arr.sum(xs)` or `Arr.sumBy(xs, fn)` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferArrSum {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace branded number type assertions (e.g., `as Int`) with corresponding functions (e.g., `asInt()`) from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferAsInt {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `typeof u === "object" && u !== null` with `isNonNullObject(u)` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferIsNonNullObject {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `for (let i = begin; i < end; ++i)` with `for (const i of range(begin, end))` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferRangeForLoop {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `Object.hasOwn(obj, key)` or `key in obj` with `isRecord(obj) && hasKey(obj, key)` from ts-data-forge
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferIsRecordAndHasKey {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `parseInt(x, 10)` with `Result.unwrapOkOr(Num.safeParseInt(x), Number.NaN)` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferNumSafeParseInt {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `parseFloat(x)`, `Number.parseFloat(x)`, or `Number(x)` (when x is a string) with `Result.unwrapOkOr(Num.safeParseFloat(x), Number.NaN)` from ts-data-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferNumSafeParseFloat {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Detect ts-data-forge type guard calls that perform no narrowing (the argument type already satisfies, or can never satisfy, the guard).
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace NoUnnecessaryTypeGuard {
  /**
   * ### schema
   *
   * ```json
   * [
   *   {
   *     "type": "object",
   *     "properties": {
   *       "ignore": {
   *         "type": "array",
   *         "items": {
   *           "type": "string"
   *         },
   *         "description": "Names of ts-data-forge guard functions to skip checking."
   *       }
   *     },
   *     "additionalProperties": false
   *   }
   * ]
   * ```
   */
  export type Options = NonNullable<
    RuleOptionsOf<'no-unnecessary-type-guard'>[0]
  >;

  export type RuleEntry =
    | 'off'
    | Linter.Severity
    | SpreadOptionsIfIsArray<readonly [Linter.StringSeverity, Options]>;
}

/**
 * @description Prefer a direct `=== null` / `!== undefined` comparison over calling `isNull`, `isNotNull`, `isUndefined`, or `isNotUndefined` with an explicit argument (those guards are intended for point-free use such as `xs.filter(isNotUndefined)`).
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferComparisonOverNullishGuard {
  export type RuleEntry = Linter.StringSeverity;
}

export type EslintTsDataForgeRules = Readonly<{
  'ts-data-forge/prefer-canonical-array-slicing': PreferCanonicalArraySlicing.RuleEntry;
  'ts-data-forge/prefer-canonical-length-guard': PreferCanonicalLengthGuard.RuleEntry;
  'ts-data-forge/prefer-canonical-length-cast': PreferCanonicalLengthCast.RuleEntry;
  'ts-data-forge/prefer-arr-is-array': PreferArrIsArray.RuleEntry;
  'ts-data-forge/prefer-arr-sum': PreferArrSum.RuleEntry;
  'ts-data-forge/prefer-as-int': PreferAsInt.RuleEntry;
  'ts-data-forge/prefer-is-non-null-object': PreferIsNonNullObject.RuleEntry;
  'ts-data-forge/prefer-range-for-loop': PreferRangeForLoop.RuleEntry;
  'ts-data-forge/prefer-is-record-and-has-key': PreferIsRecordAndHasKey.RuleEntry;
  'ts-data-forge/prefer-num-safe-parse-int': PreferNumSafeParseInt.RuleEntry;
  'ts-data-forge/prefer-num-safe-parse-float': PreferNumSafeParseFloat.RuleEntry;
  'ts-data-forge/no-unnecessary-type-guard': NoUnnecessaryTypeGuard.RuleEntry;
  'ts-data-forge/prefer-comparison-over-nullish-guard': PreferComparisonOverNullishGuard.RuleEntry;
}>;

export type EslintTsDataForgeRulesOption = Readonly<{
  'ts-data-forge/no-unnecessary-type-guard': NoUnnecessaryTypeGuard.Options;
}>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
expectType<
  keyof EslintTsDataForgeRules,
  `ts-data-forge/${keyof typeof tsDataForgeRules}`
>('=');
