/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type TSESLint } from '@typescript-eslint/utils';
import { type Linter } from 'eslint';
import { type TypeEq } from 'ts-type-forge';
import { type tsTypeForgeRules } from './rules/index.mjs';

type SpreadOptionsIfIsArray<
  T extends readonly [Linter.StringSeverity, unknown],
> = T[1] extends readonly unknown[]
  ? readonly [Linter.StringSeverity, ...T[1]]
  : T;

/**
 * Extracts the options tuple type of a rule from its TypeScript
 * implementation, so that option types stay in sync with the rule source
 * without converting `meta.schema` (JSON Schema) back into TypeScript types.
 */
type RuleOptionsOf<Name extends keyof typeof tsTypeForgeRules> =
  (typeof tsTypeForgeRules)[Name] extends TSESLint.RuleModule<
    infer _MessageIds extends string,
    infer Options extends readonly unknown[]
  >
    ? Options
    : never;

/**
 * @description Replace uniform tuple spellings such as `[V, ...V[]]` / `[V, V, ...V[]]` / `[V, V, V]` with the canonical ts-type-forge tuple type.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferCanonicalLengthConstrainedTuple {
  /**
   * ### schema
   *
   * ```json
   * [
   *   {
   *     "type": "object",
   *     "properties": {
   *       "importStyle": {
   *         "type": "string",
   *         "enum": [
   *           "global",
   *           "named"
   *         ],
   *         "description": "How the ts-type-forge type is brought into scope. 'named' (default) makes the autofix add the corresponding `import { type … } from 'ts-type-forge';` when the name is not imported yet; 'global' assumes the ambient globals of `ts-type-forge/global` and never touches imports."
   *       },
   *       "maxLength": {
   *         "type": "integer",
   *         "minimum": 2,
   *         "description": "Longest tuple the rule rewrites (default 10). Longer tuples are usually spelled out on purpose, and the named form stops being more readable."
   *       }
   *     },
   *     "additionalProperties": false
   *   }
   * ]
   * ```
   */
  export type Options = NonNullable<
    RuleOptionsOf<'prefer-canonical-length-constrained-tuple'>[0]
  >;

  export type RuleEntry =
    | 'off'
    | Linter.Severity
    | SpreadOptionsIfIsArray<readonly [Linter.StringSeverity, Options]>;
}

export type EslintTsTypeForgeRules = Readonly<{
  'ts-type-forge/prefer-canonical-length-constrained-tuple': PreferCanonicalLengthConstrainedTuple.RuleEntry;
}>;

export type EslintTsTypeForgeRulesOption = Readonly<{
  'ts-type-forge/prefer-canonical-length-constrained-tuple': PreferCanonicalLengthConstrainedTuple.Options;
}>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
type AssertTrue<B extends true> = B;

export type RuleNamesAreInSync = AssertTrue<
  TypeEq<
    keyof EslintTsTypeForgeRules,
    `ts-type-forge/${keyof typeof tsTypeForgeRules}`
  >
>;
