/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type TSESLint } from '@typescript-eslint/utils';
import { type Linter } from 'eslint';
import { type TypeEq } from 'ts-type-forge';
import { type tsTypeForgeRules } from './rules/index.mjs';

type SpreadOptionsIfIsArray<
  T extends readonly [Linter.StringSeverity, unknown],
> = T[1] extends readonly unknown[]
  ? readonly [Linter.StringSeverity, ...T[1]]
  : T;

/**
 * Extracts the options tuple type of a rule from its TypeScript
 * implementation, so that option types stay in sync with the rule source
 * without converting `meta.schema` (JSON Schema) back into TypeScript types.
 */
type RuleOptionsOf<Name extends keyof typeof tsTypeForgeRules> =
  (typeof tsTypeForgeRules)[Name] extends TSESLint.RuleModule<
    infer _MessageIds extends string,
    infer Options extends readonly unknown[]
  >
    ? Options
    : never;

/**
 * @description Replace the `readonly [V, ...V[]]` tuple spelling with `NonEmptyArray<V>` from ts-type-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferNonEmptyArray {
  /**
   * ### schema
   *
   * ```json
   * [
   *   {
   *     "type": "object",
   *     "properties": {
   *       "importStyle": {
   *         "type": "string",
   *         "enum": [
   *           "global",
   *           "named"
   *         ],
   *         "description": "How `NonEmptyArray` is brought into scope. 'global' (default) assumes the ambient globals of `ts-type-forge/global` and never touches imports; 'named' makes the autofix add `import { type NonEmptyArray } from 'ts-type-forge';` when the name is not imported yet."
   *       }
   *     },
   *     "additionalProperties": false
   *   }
   * ]
   * ```
   */
  export type Options = NonNullable<RuleOptionsOf<'prefer-non-empty-array'>[0]>;

  export type RuleEntry =
    | 'off'
    | Linter.Severity
    | SpreadOptionsIfIsArray<readonly [Linter.StringSeverity, Options]>;
}

export type EslintTsTypeForgeRules = Readonly<{
  'ts-type-forge/prefer-non-empty-array': PreferNonEmptyArray.RuleEntry;
}>;

export type EslintTsTypeForgeRulesOption = Readonly<{
  'ts-type-forge/prefer-non-empty-array': PreferNonEmptyArray.Options;
}>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
type AssertTrue<B extends true> = B;

export type RuleNamesAreInSync = AssertTrue<
  TypeEq<
    keyof EslintTsTypeForgeRules,
    `ts-type-forge/${keyof typeof tsTypeForgeRules}`
  >
>;
