export const autoImportDef = {
  '@noshiro/syncflow': [
    'auditTime',
    'combine',
    'createEventEmitter',
    'createVoidEventEmitter',
    'debounceTime',
    'filter',
    'fromPromise',
    'map',
    'mapMaybe',
    'mapResultErr',
    'mapResultOk',
    'mapTo',
    'mapWithIndex',
    'of',
    'pairwise',
    'pluck',
    'scan',
    'setInitialValue',
    'skip',
    'skipIfNoChange',
    'source',
    'throttleTime',
    'unwrapMaybe',
    'unwrapResultErr',
    'unwrapResultOk',
    'withCurrentValueFrom',
    'zip',
  ],
} as const;
