export const eslintNoRestrictedImportsDef = {
  name: '@noshiro/syncflow',
  importNames: [
    'auditTime',
    'combine',
    'createEventEmitter',
    'createVoidEventEmitter',
    'debounceTime',
    'filter',
    'fromPromise',
    'map',
    'mapMaybe',
    'mapResultErr',
    'mapResultOk',
    'mapTo',
    'mapWithIndex',
    'of',
    'pairwise',
    'pluck',
    'scan',
    'setInitialValue',
    'skip',
    'skipIfNoChange',
    'source',
    'throttleTime',
    'unwrapMaybe',
    'unwrapResultErr',
    'unwrapResultOk',
    'withCurrentValueFrom',
    'zip',
    'InitializedObservable',
    'Observable',
    'Subscription',
  ],
  message: 'use global variable instead.',
};
