import {
  type auditTime as _auditTime,
  type auditTimeI as _auditTimeI,
  type combineLatest as _combineLatest,
  type combineLatestI as _combineLatestI,
  type createBooleanState as _createBooleanState,
  type createEventEmitter as _createEventEmitter,
  type createReducer as _createReducer,
  type createState as _createState,
  type createVoidEventEmitter as _createVoidEventEmitter,
  type debounceTime as _debounceTime,
  type debounceTimeI as _debounceTimeI,
  type distinctUntilChanged as _distinctUntilChanged,
  type distinctUntilChangedI as _distinctUntilChangedI,
  type filter as _filter,
  type fromPromise as _fromPromise,
  type InitializedObservable as _InitializedObservable,
  type map as _map,
  type mapI as _mapI,
  type mapMaybe as _mapMaybe,
  type mapMaybeI as _mapMaybeI,
  type mapResultErr as _mapResultErr,
  type mapResultErrI as _mapResultErrI,
  type mapResultOk as _mapResultOk,
  type mapResultOkI as _mapResultOkI,
  type mapTo as _mapTo,
  type mapToI as _mapToI,
  type mapWithIndex as _mapWithIndex,
  type mapWithIndexI as _mapWithIndexI,
  type Observable as _Observable,
  type of as _of,
  type pairwise as _pairwise,
  type pluck as _pluck,
  type pluckI as _pluckI,
  type scan as _scan,
  type skip as _skip,
  type source as _source,
  type Subscription as _Subscription,
  type throttleTime as _throttleTime,
  type throttleTimeI as _throttleTimeI,
  type unwrapMaybe as _unwrapMaybe,
  type unwrapMaybeI as _unwrapMaybeI,
  type unwrapResultErr as _unwrapResultErr,
  type unwrapResultErrI as _unwrapResultErrI,
  type unwrapResultOk as _unwrapResultOk,
  type unwrapResultOkI as _unwrapResultOkI,
  type withInitialValue as _withInitialValue,
  type withLatestFrom as _withLatestFrom,
  type withLatestFromI as _withLatestFromI,
  type zip as _zip,
  type zipI as _zipI,
} from '@noshiro/syncflow';

declare global {
  type InitializedObservable<A> = _InitializedObservable<A>;
  type Observable<A> = _Observable<A>;
  type Subscription = _Subscription;

  /* custom types */

  const auditTime: typeof _auditTime;
  const auditTimeI: typeof _auditTimeI;
  const combineLatest: typeof _combineLatest;
  const combineLatestI: typeof _combineLatestI;
  const createBooleanState: typeof _createBooleanState;
  const createEventEmitter: typeof _createEventEmitter;
  const createReducer: typeof _createReducer;
  const createState: typeof _createState;
  const createVoidEventEmitter: typeof _createVoidEventEmitter;
  const debounceTime: typeof _debounceTime;
  const debounceTimeI: typeof _debounceTimeI;
  const distinctUntilChanged: typeof _distinctUntilChanged;
  const distinctUntilChangedI: typeof _distinctUntilChangedI;
  const filter: typeof _filter;
  const fromPromise: typeof _fromPromise;
  const map: typeof _map;
  const mapI: typeof _mapI;
  const mapMaybe: typeof _mapMaybe;
  const mapMaybeI: typeof _mapMaybeI;
  const mapResultErr: typeof _mapResultErr;
  const mapResultErrI: typeof _mapResultErrI;
  const mapResultOk: typeof _mapResultOk;
  const mapResultOkI: typeof _mapResultOkI;
  const mapTo: typeof _mapTo;
  const mapToI: typeof _mapToI;
  const mapWithIndex: typeof _mapWithIndex;
  const mapWithIndexI: typeof _mapWithIndexI;
  const of: typeof _of;
  const pairwise: typeof _pairwise;
  const pluck: typeof _pluck;
  const pluckI: typeof _pluckI;
  const scan: typeof _scan;
  const skip: typeof _skip;
  const source: typeof _source;
  const throttleTime: typeof _throttleTime;
  const throttleTimeI: typeof _throttleTimeI;
  const unwrapMaybe: typeof _unwrapMaybe;
  const unwrapMaybeI: typeof _unwrapMaybeI;
  const unwrapResultErr: typeof _unwrapResultErr;
  const unwrapResultErrI: typeof _unwrapResultErrI;
  const unwrapResultOk: typeof _unwrapResultOk;
  const unwrapResultOkI: typeof _unwrapResultOkI;
  const withInitialValue: typeof _withInitialValue;
  const withLatestFrom: typeof _withLatestFrom;
  const withLatestFromI: typeof _withLatestFromI;
  const zip: typeof _zip;
  const zipI: typeof _zipI;

  /* custom variables */
}
