import { tp } from '@noshiro/ts-utils';

export const injectModulesDef = Object.fromEntries(
  [
    'auditTime',
    'combine',
    'createEventEmitter',
    'createVoidEventEmitter',
    'debounceTime',
    'filter',
    'fromPromise',
    'map',
    'mapMaybe',
    'mapResultErr',
    'mapResultOk',
    'mapTo',
    'mapWithIndex',
    'of',
    'pairwise',
    'pluck',
    'scan',
    'setInitialValue',
    'skip',
    'skipIfNoChange',
    'source',
    'throttleTime',
    'unwrapMaybe',
    'unwrapResultErr',
    'unwrapResultOk',
    'withCurrentValueFrom',
    'zip',
  ].map((key) => tp(key, tp('@noshiro/syncflow', key))),
);
