import { withDefaultOption, type EslintPluginRules } from '../types/index.mjs';

export const eslintPluginRules = {
  'eslint-plugin/consistent-output': withDefaultOption('error'),
  'eslint-plugin/fixer-return': 'error',
  'eslint-plugin/meta-property-ordering': withDefaultOption('error'),
  'eslint-plugin/no-deprecated-context-methods': 'error',
  'eslint-plugin/no-deprecated-report-api': 'error',
  'eslint-plugin/no-identical-tests': 'error',
  'eslint-plugin/no-missing-message-ids': 'error',
  'eslint-plugin/no-missing-placeholders': 'error',
  'eslint-plugin/no-only-tests': 'error',
  'eslint-plugin/no-property-in-node': withDefaultOption('error'),
  'eslint-plugin/no-unused-message-ids': 'error',
  'eslint-plugin/no-unused-placeholders': 'error',
  'eslint-plugin/no-useless-token-range': 'error',
  'eslint-plugin/prefer-message-ids': 'error',
  'eslint-plugin/prefer-object-rule': 'error',
  'eslint-plugin/prefer-output-null': 'error',
  'eslint-plugin/prefer-placeholders': 'error',
  'eslint-plugin/prefer-replace-text': 'error',
  'eslint-plugin/report-message-format': withDefaultOption('error'),
  'eslint-plugin/require-meta-docs-description': withDefaultOption('error'),
  'eslint-plugin/require-meta-docs-recommended': withDefaultOption('error'),
  'eslint-plugin/require-meta-docs-url': withDefaultOption('error'),
  'eslint-plugin/require-meta-fixable': withDefaultOption('error'),
  'eslint-plugin/require-meta-has-suggestions': 'error',
  'eslint-plugin/require-meta-schema-description': 'error',
  'eslint-plugin/require-meta-schema': withDefaultOption('error'),
  'eslint-plugin/require-meta-type': 'error',
  'eslint-plugin/test-case-property-ordering': withDefaultOption('error'),
  'eslint-plugin/test-case-shorthand-strings': withDefaultOption('error'),
  'eslint-plugin/no-meta-schema-default': 'error',
  'eslint-plugin/require-meta-default-options': 'error',
  'eslint-plugin/no-meta-replaced-by': 'error',
  'eslint-plugin/require-test-case-name': withDefaultOption('error'),
  'eslint-plugin/unique-test-case-names': 'error',
  'eslint-plugin/no-matching-violation-suggest-message-ids': 'error',
} as const satisfies EslintPluginRules;
