import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { $, Result } from 'ts-repo-utils';
import { tsDataForgeRules } from '../../src/rules/rules.mjs';
import { workspaceRootPath } from '../workspace-root-path.mjs';

const ruleTypesPath = path.resolve(workspaceRootPath, './src/rule-types.mts');

const pluginPrefix = 'ts-data-forge';

type RuleInfo = Readonly<{
  /** Rule name without the plugin prefix (e.g. `'prefer-arr-is-array'`). */
  name: string;
  /** PascalCase namespace name (e.g. `'PreferArrIsArray'`). */
  namespaceName: string;
  description: string;
  type: string;
  deprecated: boolean;
  fixable: string;
  /** `meta.schema`, embedded as JSON in the `Options` JSDoc. */
  schema: unknown;
  hasOptions: boolean;
}>;

const main = async (): Promise<void> => {
  const rules = Object.entries(tsDataForgeRules).map(([name, { meta }]) => {
    const description = meta.docs?.description;

    if (description === undefined) {
      console.error(`Rule "${name}" has no \`meta.docs.description\`.`);

      process.exit(1);
    }

    const schema: unknown = meta.schema;

    return {
      name,
      namespaceName: toPascalCase(name),
      description,
      type: meta.type,
      deprecated: meta.deprecated !== undefined && meta.deprecated !== false,
      fixable: meta.fixable ?? 'false',
      schema,
      hasOptions: Array.isArray(schema)
        ? schema.length > 0
        : schema !== undefined && schema !== false,
    } as const satisfies RuleInfo;
  });

  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await fs.writeFile(ruleTypesPath, generateFileContent(rules));

  // Normalize import order and line wrapping with the repo's Prettier config.
  const fmtResult = await $(`pnpm run z:prettier "${ruleTypesPath}"`);

  if (Result.isErr(fmtResult)) {
    console.error(
      `Failed to format the generated file: ${fmtResult.value.message}`,
    );

    process.exit(1);
  }

  console.info(
    `Generated ${path.relative(workspaceRootPath, ruleTypesPath)} (${rules.length} rules)`,
  );
};

const generateFileContent = (rules: readonly RuleInfo[]): string => {
  const hasAnyOptions = rules.some((rule) => rule.hasOptions);

  const optionRules = rules.filter((rule) => rule.hasOptions);

  return [
    '/* cSpell:disable */',
    '',
    '// This file is auto-generated by `pnpm run gen:rule-types`',
    '// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.',
    '',
    ...(hasAnyOptions
      ? ["import { type TSESLint } from '@typescript-eslint/utils';"]
      : []),
    "import { type Linter } from 'eslint';",
    "import { expectType } from 'ts-data-forge';",
    "import { type tsDataForgeRules } from './rules/index.mjs';",
    '',
    ...(hasAnyOptions
      ? [
          'type SpreadOptionsIfIsArray<',
          '  T extends readonly [Linter.StringSeverity, unknown],',
          '> = T[1] extends readonly unknown[]',
          '  ? readonly [Linter.StringSeverity, ...T[1]]',
          '  : T;',
          '',
          '/**',
          ' * Extracts the options tuple type of a rule from its TypeScript',
          ' * implementation, so that option types stay in sync with the rule source',
          ' * without converting `meta.schema` (JSON Schema) back into TypeScript types.',
          ' */',
          'type RuleOptionsOf<Name extends keyof typeof tsDataForgeRules> =',
          '  (typeof tsDataForgeRules)[Name] extends TSESLint.RuleModule<',
          '    infer _MessageIds extends string,',
          '    infer Options extends readonly unknown[]',
          '  >',
          '    ? Options',
          '    : never;',
          '',
        ]
      : []),
    ...rules.flatMap((rule) => [...generateRuleNamespace(rule), '']),
    'export type EslintTsDataForgeRules = Readonly<{',
    ...rules.map(
      (rule) =>
        `  '${pluginPrefix}/${rule.name}': ${rule.namespaceName}.RuleEntry;`,
    ),
    '}>;',
    '',
    'export type EslintTsDataForgeRulesOption = Readonly<{',
    ...optionRules.map(
      (rule) =>
        `  '${pluginPrefix}/${rule.name}': ${rule.namespaceName}.Options;`,
    ),
    '}>;',
    '',
    '// If this assertion fails to type-check, this generated file has drifted from',
    '// the actual plugin rules — re-run `pnpm run gen:rule-types`.',
    'expectType<',
    '  keyof EslintTsDataForgeRules,',
    `  \`${pluginPrefix}/\${keyof typeof tsDataForgeRules}\``,
    ">('=');",
    '',
  ].join('\n');
};

const generateRuleNamespace = (rule: RuleInfo): readonly string[] =>
  [
    '/**',
    ` * @description ${rule.description}`,
    ' *',
    ...generateMetaTable(rule),
    ' */',
    `namespace ${rule.namespaceName} {`,
    ...(rule.hasOptions
      ? ([
          ...generateSchemaJsdoc(rule.schema),
          `  export type Options = NonNullable<RuleOptionsOf<'${rule.name}'>[0]>;`,
          '',
          '  export type RuleEntry =',
          "    | 'off'",
          '    | Linter.Severity',
          '    | SpreadOptionsIfIsArray<readonly [Linter.StringSeverity, Options]>;',
        ] as const)
      : (['  export type RuleEntry = Linter.StringSeverity;'] as const)),
    '}',
  ] as const;

const generateMetaTable = (rule: RuleInfo): readonly string[] => {
  const rows = [
    ['type', rule.type],
    ['deprecated', String(rule.deprecated)],
    ['fixable', rule.fixable],
  ] as const;

  const keyWidth = Math.max('key'.length, ...rows.map(([key]) => key.length));

  const valueWidth = Math.max(
    'value'.length,
    ...rows.map(([, value]) => value.length),
  );

  return [
    ' *  ```md',
    ` *  | ${'key'.padEnd(keyWidth)} | ${'value'.padEnd(valueWidth)} |`,
    ` *  | :${'-'.repeat(keyWidth - 1)} | :${'-'.repeat(valueWidth - 1)} |`,
    ...rows.map(
      ([key, value]) =>
        ` *  | ${key.padEnd(keyWidth)} | ${value.padEnd(valueWidth)} |`,
    ),
    ' *  ```',
  ];
};

const generateSchemaJsdoc = (schema: unknown): readonly string[] =>
  [
    '  /**',
    '   * ### schema',
    '   *',
    '   * ```json',
    ...JSON.stringify(schema, undefined, 2)
      .split('\n')
      .map((line) => `   * ${line}`.trimEnd()),
    '   * ```',
    '   */',
  ] as const;

const toPascalCase = (kebabCase: string): string =>
  kebabCase
    .split('-')
    .map((word) => `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`)
    .join('');

await main();
