import { type RevealedBlock, type TileName } from '../types';

export const revealedBlockToTiles = (
  revealedBlock: RevealedBlock
): ArrayOfLength<3, TileName> | ArrayOfLength<4, TileName> =>
  match(revealedBlock, {
    // Ankantsu
    'Ankantsu-Manzu1': ['Manzu1', 'Manzu1', 'Manzu1', 'Manzu1'],
    'Ankantsu-Manzu2': ['Manzu2', 'Manzu2', 'Manzu2', 'Manzu2'],
    'Ankantsu-Manzu3': ['Manzu3', 'Manzu3', 'Manzu3', 'Manzu3'],
    'Ankantsu-Manzu4': ['Manzu4', 'Manzu4', 'Manzu4', 'Manzu4'],
    'Ankantsu-Manzu5': ['Manzu5', 'Manzu5', 'Manzu5', 'Manzu5'],
    'Ankantsu-Manzu5-withAka': ['Manzu5', 'Manzu5', 'Manzu5', 'AkaManzu5'],
    'Ankantsu-Manzu6': ['Manzu6', 'Manzu6', 'Manzu6', 'Manzu6'],
    'Ankantsu-Manzu7': ['Manzu7', 'Manzu7', 'Manzu7', 'Manzu7'],
    'Ankantsu-Manzu8': ['Manzu8', 'Manzu8', 'Manzu8', 'Manzu8'],
    'Ankantsu-Manzu9': ['Manzu9', 'Manzu9', 'Manzu9', 'Manzu9'],
    'Ankantsu-Pinzu1': ['Pinzu1', 'Pinzu1', 'Pinzu1', 'Pinzu1'],
    'Ankantsu-Pinzu2': ['Pinzu2', 'Pinzu2', 'Pinzu2', 'Pinzu2'],
    'Ankantsu-Pinzu3': ['Pinzu3', 'Pinzu3', 'Pinzu3', 'Pinzu3'],
    'Ankantsu-Pinzu4': ['Pinzu4', 'Pinzu4', 'Pinzu4', 'Pinzu4'],
    'Ankantsu-Pinzu5': ['Pinzu5', 'Pinzu5', 'Pinzu5', 'Pinzu5'],
    'Ankantsu-Pinzu5-withAka': ['Pinzu5', 'Pinzu5', 'Pinzu5', 'AkaPinzu5'],
    'Ankantsu-Pinzu6': ['Pinzu6', 'Pinzu6', 'Pinzu6', 'Pinzu6'],
    'Ankantsu-Pinzu7': ['Pinzu7', 'Pinzu7', 'Pinzu7', 'Pinzu7'],
    'Ankantsu-Pinzu8': ['Pinzu8', 'Pinzu8', 'Pinzu8', 'Pinzu8'],
    'Ankantsu-Pinzu9': ['Pinzu9', 'Pinzu9', 'Pinzu9', 'Pinzu9'],
    'Ankantsu-Sozu1': ['Sozu1', 'Sozu1', 'Sozu1', 'Sozu1'],
    'Ankantsu-Sozu2': ['Sozu2', 'Sozu2', 'Sozu2', 'Sozu2'],
    'Ankantsu-Sozu3': ['Sozu3', 'Sozu3', 'Sozu3', 'Sozu3'],
    'Ankantsu-Sozu4': ['Sozu4', 'Sozu4', 'Sozu4', 'Sozu4'],
    'Ankantsu-Sozu5': ['Sozu5', 'Sozu5', 'Sozu5', 'Sozu5'],
    'Ankantsu-Sozu5-withAka': ['Sozu5', 'Sozu5', 'Sozu5', 'AkaSozu5'],
    'Ankantsu-Sozu6': ['Sozu6', 'Sozu6', 'Sozu6', 'Sozu6'],
    'Ankantsu-Sozu7': ['Sozu7', 'Sozu7', 'Sozu7', 'Sozu7'],
    'Ankantsu-Sozu8': ['Sozu8', 'Sozu8', 'Sozu8', 'Sozu8'],
    'Ankantsu-Sozu9': ['Sozu9', 'Sozu9', 'Sozu9', 'Sozu9'],
    'Ankantsu-Ton': ['Ton', 'Ton', 'Ton', 'Ton'],
    'Ankantsu-Nan': ['Nan', 'Nan', 'Nan', 'Nan'],
    'Ankantsu-Sha': ['Sha', 'Sha', 'Sha', 'Sha'],
    'Ankantsu-Pei': ['Pei', 'Pei', 'Pei', 'Pei'],
    'Ankantsu-Haku': ['Haku', 'Haku', 'Haku', 'Haku'],
    'Ankantsu-Hatsu': ['Hatsu', 'Hatsu', 'Hatsu', 'Hatsu'],
    'Ankantsu-Chun': ['Chun', 'Chun', 'Chun', 'Chun'],
    // Minkantsu
    'Minkantsu-Manzu1': ['Manzu1', 'Manzu1', 'Manzu1', 'Manzu1'],
    'Minkantsu-Manzu2': ['Manzu2', 'Manzu2', 'Manzu2', 'Manzu2'],
    'Minkantsu-Manzu3': ['Manzu3', 'Manzu3', 'Manzu3', 'Manzu3'],
    'Minkantsu-Manzu4': ['Manzu4', 'Manzu4', 'Manzu4', 'Manzu4'],
    'Minkantsu-Manzu5': ['Manzu5', 'Manzu5', 'Manzu5', 'Manzu5'],
    'Minkantsu-Manzu5-withAka': ['Manzu5', 'Manzu5', 'Manzu5', 'AkaManzu5'],
    'Minkantsu-Manzu6': ['Manzu6', 'Manzu6', 'Manzu6', 'Manzu6'],
    'Minkantsu-Manzu7': ['Manzu7', 'Manzu7', 'Manzu7', 'Manzu7'],
    'Minkantsu-Manzu8': ['Manzu8', 'Manzu8', 'Manzu8', 'Manzu8'],
    'Minkantsu-Manzu9': ['Manzu9', 'Manzu9', 'Manzu9', 'Manzu9'],
    'Minkantsu-Pinzu1': ['Pinzu1', 'Pinzu1', 'Pinzu1', 'Pinzu1'],
    'Minkantsu-Pinzu2': ['Pinzu2', 'Pinzu2', 'Pinzu2', 'Pinzu2'],
    'Minkantsu-Pinzu3': ['Pinzu3', 'Pinzu3', 'Pinzu3', 'Pinzu3'],
    'Minkantsu-Pinzu4': ['Pinzu4', 'Pinzu4', 'Pinzu4', 'Pinzu4'],
    'Minkantsu-Pinzu5': ['Pinzu5', 'Pinzu5', 'Pinzu5', 'Pinzu5'],
    'Minkantsu-Pinzu5-withAka': ['Pinzu5', 'Pinzu5', 'Pinzu5', 'AkaPinzu5'],
    'Minkantsu-Pinzu6': ['Pinzu6', 'Pinzu6', 'Pinzu6', 'Pinzu6'],
    'Minkantsu-Pinzu7': ['Pinzu7', 'Pinzu7', 'Pinzu7', 'Pinzu7'],
    'Minkantsu-Pinzu8': ['Pinzu8', 'Pinzu8', 'Pinzu8', 'Pinzu8'],
    'Minkantsu-Pinzu9': ['Pinzu9', 'Pinzu9', 'Pinzu9', 'Pinzu9'],
    'Minkantsu-Sozu1': ['Sozu1', 'Sozu1', 'Sozu1', 'Sozu1'],
    'Minkantsu-Sozu2': ['Sozu2', 'Sozu2', 'Sozu2', 'Sozu2'],
    'Minkantsu-Sozu3': ['Sozu3', 'Sozu3', 'Sozu3', 'Sozu3'],
    'Minkantsu-Sozu4': ['Sozu4', 'Sozu4', 'Sozu4', 'Sozu4'],
    'Minkantsu-Sozu5': ['Sozu5', 'Sozu5', 'Sozu5', 'Sozu5'],
    'Minkantsu-Sozu5-withAka': ['Sozu5', 'Sozu5', 'Sozu5', 'AkaSozu5'],
    'Minkantsu-Sozu6': ['Sozu6', 'Sozu6', 'Sozu6', 'Sozu6'],
    'Minkantsu-Sozu7': ['Sozu7', 'Sozu7', 'Sozu7', 'Sozu7'],
    'Minkantsu-Sozu8': ['Sozu8', 'Sozu8', 'Sozu8', 'Sozu8'],
    'Minkantsu-Sozu9': ['Sozu9', 'Sozu9', 'Sozu9', 'Sozu9'],
    'Minkantsu-Ton': ['Ton', 'Ton', 'Ton', 'Ton'],
    'Minkantsu-Nan': ['Nan', 'Nan', 'Nan', 'Nan'],
    'Minkantsu-Sha': ['Sha', 'Sha', 'Sha', 'Sha'],
    'Minkantsu-Pei': ['Pei', 'Pei', 'Pei', 'Pei'],
    'Minkantsu-Haku': ['Haku', 'Haku', 'Haku', 'Haku'],
    'Minkantsu-Hatsu': ['Hatsu', 'Hatsu', 'Hatsu', 'Hatsu'],
    'Minkantsu-Chun': ['Chun', 'Chun', 'Chun', 'Chun'],
    // Kotsu
    'Kotsu-Manzu1': ['Manzu1', 'Manzu1', 'Manzu1'],
    'Kotsu-Manzu2': ['Manzu2', 'Manzu2', 'Manzu2'],
    'Kotsu-Manzu3': ['Manzu3', 'Manzu3', 'Manzu3'],
    'Kotsu-Manzu4': ['Manzu4', 'Manzu4', 'Manzu4'],
    'Kotsu-Manzu5': ['Manzu5', 'Manzu5', 'Manzu5'],
    'Kotsu-Manzu5-withAka': ['Manzu5', 'Manzu5', 'AkaManzu5'],
    'Kotsu-Manzu6': ['Manzu6', 'Manzu6', 'Manzu6'],
    'Kotsu-Manzu7': ['Manzu7', 'Manzu7', 'Manzu7'],
    'Kotsu-Manzu8': ['Manzu8', 'Manzu8', 'Manzu8'],
    'Kotsu-Manzu9': ['Manzu9', 'Manzu9', 'Manzu9'],
    'Kotsu-Pinzu1': ['Pinzu1', 'Pinzu1', 'Pinzu1'],
    'Kotsu-Pinzu2': ['Pinzu2', 'Pinzu2', 'Pinzu2'],
    'Kotsu-Pinzu3': ['Pinzu3', 'Pinzu3', 'Pinzu3'],
    'Kotsu-Pinzu4': ['Pinzu4', 'Pinzu4', 'Pinzu4'],
    'Kotsu-Pinzu5': ['Pinzu5', 'Pinzu5', 'Pinzu5'],
    'Kotsu-Pinzu5-withAka': ['Pinzu5', 'Pinzu5', 'AkaPinzu5'],
    'Kotsu-Pinzu6': ['Pinzu6', 'Pinzu6', 'Pinzu6'],
    'Kotsu-Pinzu7': ['Pinzu7', 'Pinzu7', 'Pinzu7'],
    'Kotsu-Pinzu8': ['Pinzu8', 'Pinzu8', 'Pinzu8'],
    'Kotsu-Pinzu9': ['Pinzu9', 'Pinzu9', 'Pinzu9'],
    'Kotsu-Sozu1': ['Sozu1', 'Sozu1', 'Sozu1'],
    'Kotsu-Sozu2': ['Sozu2', 'Sozu2', 'Sozu2'],
    'Kotsu-Sozu3': ['Sozu3', 'Sozu3', 'Sozu3'],
    'Kotsu-Sozu4': ['Sozu4', 'Sozu4', 'Sozu4'],
    'Kotsu-Sozu5': ['Sozu5', 'Sozu5', 'Sozu5'],
    'Kotsu-Sozu5-withAka': ['Sozu5', 'Sozu5', 'AkaSozu5'],
    'Kotsu-Sozu6': ['Sozu6', 'Sozu6', 'Sozu6'],
    'Kotsu-Sozu7': ['Sozu7', 'Sozu7', 'Sozu7'],
    'Kotsu-Sozu8': ['Sozu8', 'Sozu8', 'Sozu8'],
    'Kotsu-Sozu9': ['Sozu9', 'Sozu9', 'Sozu9'],
    'Kotsu-Ton': ['Ton', 'Ton', 'Ton'],
    'Kotsu-Nan': ['Nan', 'Nan', 'Nan'],
    'Kotsu-Sha': ['Sha', 'Sha', 'Sha'],
    'Kotsu-Pei': ['Pei', 'Pei', 'Pei'],
    'Kotsu-Haku': ['Haku', 'Haku', 'Haku'],
    'Kotsu-Hatsu': ['Hatsu', 'Hatsu', 'Hatsu'],
    'Kotsu-Chun': ['Chun', 'Chun', 'Chun'],
    // Shuntsu
    Manzu123: ['Manzu1', 'Manzu2', 'Manzu3'],
    Manzu234: ['Manzu2', 'Manzu3', 'Manzu4'],
    Manzu345: ['Manzu3', 'Manzu4', 'Manzu5'],
    'Manzu345-withAka': ['Manzu3', 'Manzu4', 'Manzu5'],
    Manzu456: ['Manzu4', 'Manzu5', 'Manzu6'],
    'Manzu456-withAka': ['Manzu4', 'Manzu5', 'Manzu6'],
    Manzu567: ['Manzu5', 'Manzu6', 'Manzu7'],
    'Manzu567-withAka': ['Manzu5', 'Manzu6', 'Manzu7'],
    Manzu678: ['Manzu6', 'Manzu7', 'Manzu8'],
    Manzu789: ['Manzu7', 'Manzu8', 'Manzu9'],
    Pinzu123: ['Pinzu1', 'Pinzu2', 'Pinzu3'],
    Pinzu234: ['Pinzu2', 'Pinzu3', 'Pinzu4'],
    Pinzu345: ['Pinzu3', 'Pinzu4', 'Pinzu5'],
    'Pinzu345-withAka': ['Pinzu3', 'Pinzu4', 'Pinzu5'],
    Pinzu456: ['Pinzu4', 'Pinzu5', 'Pinzu6'],
    'Pinzu456-withAka': ['Pinzu4', 'Pinzu5', 'Pinzu6'],
    Pinzu567: ['Pinzu5', 'Pinzu6', 'Pinzu7'],
    'Pinzu567-withAka': ['Pinzu5', 'Pinzu6', 'Pinzu7'],
    Pinzu678: ['Pinzu6', 'Pinzu7', 'Pinzu8'],
    Pinzu789: ['Pinzu7', 'Pinzu8', 'Pinzu9'],
    Sozu123: ['Sozu1', 'Sozu2', 'Sozu3'],
    Sozu234: ['Sozu2', 'Sozu3', 'Sozu4'],
    Sozu345: ['Sozu3', 'Sozu4', 'Sozu5'],
    'Sozu345-withAka': ['Sozu3', 'Sozu4', 'Sozu5'],
    Sozu456: ['Sozu4', 'Sozu5', 'Sozu6'],
    'Sozu456-withAka': ['Sozu4', 'Sozu5', 'Sozu6'],
    Sozu567: ['Sozu5', 'Sozu6', 'Sozu7'],
    'Sozu567-withAka': ['Sozu5', 'Sozu6', 'Sozu7'],
    Sozu678: ['Sozu6', 'Sozu7', 'Sozu8'],
    Sozu789: ['Sozu7', 'Sozu8', 'Sozu9'],
  } as const);
