import { type EslintPlaywrightRules } from '../types/index.mjs';

export const eslintPlaywrightRules: EslintPlaywrightRules = {
  /* vitest と共通のルール（設定値をなるべく合わせる） */
  'playwright/expect-expect': 'error',
  'playwright/max-expects': 'off',
  'playwright/max-nested-describe': 'error',
  'playwright/no-commented-out-tests': 'off',
  'playwright/no-conditional-expect': 'error',
  'playwright/no-conditional-in-test': 'off',
  'playwright/no-duplicate-hooks': 'error',
  'playwright/no-hooks': 'error',
  'playwright/no-restricted-matchers': [
    'error',
    {
      toBeTruthy: 'Use `.toBe(true)` instead.',
      toBeFalsy: 'Use `.toBe(false)` instead.',
    },
  ],
  'playwright/no-standalone-expect': 'error',
  'playwright/prefer-comparison-matcher': 'error',
  'playwright/prefer-equality-matcher': 'error',
  'playwright/prefer-hooks-in-order': 'error',
  'playwright/prefer-hooks-on-top': 'error',
  'playwright/prefer-strict-equal': 'error',
  'playwright/prefer-to-be': 'error',
  'playwright/prefer-to-contain': 'error',
  'playwright/prefer-to-have-length': 'error',
  'playwright/require-hook': 'off',
  'playwright/require-to-throw-message': 'error',
  'playwright/require-top-level-describe': 'off',
  'playwright/valid-describe-callback': 'error',
  'playwright/valid-expect': 'error',
  'playwright/valid-title': 'off',

  /* eslint-plugin-playwright 独自ルール */

  'playwright/missing-playwright-await': 'error',
  'playwright/no-element-handle': 'error',
  'playwright/no-eval': 'error',
  'playwright/no-focused-test': 'error',
  'playwright/no-force-option': 'error',
  'playwright/no-get-by-title': 'error',
  'playwright/no-nested-step': 'error',
  'playwright/no-networkidle': 'error',
  'playwright/no-nth-methods': 'off',
  'playwright/no-page-pause': 'error',
  'playwright/no-raw-locators': 'error',
  'playwright/no-skipped-test': 'error',
  'playwright/no-slowed-test': 'error',
  'playwright/no-unsafe-references': 'error',
  'playwright/no-useless-await': 'error',
  'playwright/no-useless-not': 'error',
  'playwright/no-wait-for-selector': 'error',
  'playwright/no-wait-for-timeout': 'error',
  'playwright/prefer-locator': 'error',
  'playwright/prefer-lowercase-title': 'error',
  'playwright/prefer-native-locators': 'error',
  'playwright/prefer-to-have-count': 'error',
  'playwright/prefer-web-first-assertions': 'error',
  'playwright/require-soft-assertions': 'error',
  'playwright/valid-expect-in-promise': 'error',
} as const;
