import { type TileName } from '../types';

export const dora2DoraHyouji = {
  Manzu1: 'Manzu9',
  Manzu2: 'Manzu1',
  Manzu3: 'Manzu2',
  Manzu4: 'Manzu3',
  Manzu5: 'Manzu4',
  Manzu6: 'Manzu5',
  Manzu7: 'Manzu6',
  Manzu8: 'Manzu7',
  Manzu9: 'Manzu8',
  Pinzu1: 'Pinzu9',
  Pinzu2: 'Pinzu1',
  Pinzu3: 'Pinzu2',
  Pinzu4: 'Pinzu3',
  Pinzu5: 'Pinzu4',
  Pinzu6: 'Pinzu5',
  Pinzu7: 'Pinzu6',
  Pinzu8: 'Pinzu7',
  Pinzu9: 'Pinzu8',
  Sozu1: 'Sozu9',
  Sozu2: 'Sozu1',
  Sozu3: 'Sozu2',
  Sozu4: 'Sozu3',
  Sozu5: 'Sozu4',
  Sozu6: 'Sozu5',
  Sozu7: 'Sozu6',
  Sozu8: 'Sozu7',
  Sozu9: 'Sozu8',
  Ton: 'Pei',
  Nan: 'Ton',
  Sha: 'Nan',
  Pei: 'Sha',
  Haku: 'Chun',
  Hatsu: 'Haku',
  Chun: 'Hatsu',
} as const satisfies Record<
  Exclude<TileName, 'AkaManzu5' | 'AkaPinzu5' | 'AkaSozu5'>,
  TileName
>;

export const doraHyouji2Dora = {
  Manzu1: 'Manzu2',
  Manzu2: 'Manzu3',
  Manzu3: 'Manzu4',
  Manzu4: 'Manzu5',
  Manzu5: 'Manzu6',
  Manzu6: 'Manzu7',
  Manzu7: 'Manzu8',
  Manzu8: 'Manzu9',
  Manzu9: 'Manzu1',
  Pinzu1: 'Pinzu2',
  Pinzu2: 'Pinzu3',
  Pinzu3: 'Pinzu4',
  Pinzu4: 'Pinzu5',
  Pinzu5: 'Pinzu6',
  Pinzu6: 'Pinzu7',
  Pinzu7: 'Pinzu8',
  Pinzu8: 'Pinzu9',
  Pinzu9: 'Pinzu1',
  Sozu1: 'Sozu2',
  Sozu2: 'Sozu3',
  Sozu3: 'Sozu4',
  Sozu4: 'Sozu5',
  Sozu5: 'Sozu6',
  Sozu6: 'Sozu7',
  Sozu7: 'Sozu8',
  Sozu8: 'Sozu9',
  Sozu9: 'Sozu1',
  Ton: 'Nan',
  Nan: 'Sha',
  Sha: 'Pei',
  Pei: 'Ton',
  Haku: 'Hatsu',
  Hatsu: 'Chun',
  Chun: 'Haku',
  AkaManzu5: 'Manzu6',
  AkaPinzu5: 'Pinzu6',
  AkaSozu5: 'Sozu6',
} as const satisfies Record<
  TileName,
  Exclude<TileName, 'AkaManzu5' | 'AkaPinzu5' | 'AkaSozu5'>
>;
