import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { formatFiles, isDirectlyExecuted, Result } from 'ts-repo-utils';
import { repositoryRootPath } from '../repository-root-path.mjs';

const commonRulesPath = path.resolve(
  repositoryRootPath,
  'agents/common-rules.md',
);

const localRulesPath = path.resolve(
  repositoryRootPath,
  'agents/local-rules.md',
);

const outputPath = path.resolve(repositoryRootPath, 'AGENTS.md');

const header = [
  '<!-- AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY. -->',
  '<!--',
  '  Generated by scripts/cmd/gen-agents-md.mts (run via `pnpm run build` or',
  '  `pnpm run agents:gen`) as the concatenation of:',
  '  - agents/common-rules.md (shared rules; vendored from the',
  '    common-agent-config repository by `pnpm run agents:sync` — edit them',
  '    there, not here)',
  '  - agents/local-rules.md (repository-specific rules; edit directly)',
  '-->',
  '',
].join('\n');

const separator = [
  '',
  '---',
  '',
  '<!-- The section below is repository-specific (agents/local-rules.md). -->',
  '',
].join('\n');

/**
 * Regenerates the root `AGENTS.md` by concatenating the shared agent
 * instructions (`agents/common-rules.md`, vendored from the
 * common-agent-config repository by `pnpm run agents:sync`) with the
 * repository-specific rules (`agents/local-rules.md`).
 */
export const genAgentsMd = async (): Promise<Result<undefined, string>> => {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    const commonContent = await fs
      .readFile(commonRulesPath, 'utf8')
      .catch(() => undefined);

    if (commonContent === undefined) {
      return Result.err(
        [
          `❌ ${path.relative(repositoryRootPath, commonRulesPath)} not found.`,
          'Vendor the shared agent instructions first by running:',
          '  pnpm run agents:sync',
        ].join('\n'),
      );
    }

    // eslint-disable-next-line security/detect-non-literal-fs-filename
    const localContent = await fs.readFile(localRulesPath, 'utf8');

    // Demote the local part's headings by one level so the concatenated
    // document keeps a single top-level heading (markdownlint MD025).
    const localContentDemoted = demoteHeadings(localContent);

    const output =
      `${header}\n${commonContent.trimEnd()}\n${separator}\n${localContentDemoted.trimEnd()}\n` as const;

    // eslint-disable-next-line security/detect-non-literal-fs-filename
    await fs.writeFile(outputPath, output, 'utf8');

    // Format the generated file with the repo's Prettier config so that the
    // committed AGENTS.md is byte-identical to what `fmt:full` would produce
    // (the local-rules.md source lives under the Prettier-ignored agents/,
    // so its embedded code blocks are otherwise not normalized).
    await formatFiles([outputPath]);

    console.info(
      `Successfully generated ${path.relative(repositoryRootPath, outputPath)}.`,
    );

    return Result.ok(undefined);
  } catch (error) {
    return Result.err(`❌ Failed to generate AGENTS.md: ${String(error)}`);
  }
};

/**
 * Shifts every ATX heading (`#`, `##`, ...) down one level, skipping fenced
 * code blocks.
 */
const demoteHeadings = (markdown: string): string => {
  let mut_inFence = false;

  return markdown
    .split('\n')
    .map((line) => {
      if (line.trimStart().startsWith('```')) {
        mut_inFence = !mut_inFence;

        return line;
      }

      return !mut_inFence && /^#{1,5} /u.test(line) ? `#${line}` : line;
    })
    .join('\n');
};

if (isDirectlyExecuted(import.meta.url)) {
  const result = await genAgentsMd();

  if (Result.isErr(result)) {
    console.error(result.value);

    process.exit(1);
  }
}
