import { generateAllGlobalDefs, toThisDir } from '@noshiro/mono-scripts';
import * as nodePath from 'node:path';
import packageJson from '../package.json' assert { type: 'json' };

await generateAllGlobalDefs({
  rootDir: nodePath.resolve(toThisDir(import.meta.url), '../'),
  packageName: packageJson.name.replace(/^@noshiro\/global-/u, '@noshiro/'),
  importsList: [
    'auditTime',
    'auditTimeI',
    'combineLatest',
    'combineLatestI',
    'createBooleanState',
    'createEventEmitter',
    'createReducer',
    'createState',
    'createVoidEventEmitter',
    'debounceTime',
    'debounceTimeI',
    'distinctUntilChanged',
    'distinctUntilChangedI',
    'filter',
    'fromPromise',
    'map',
    'mapI',
    'mapMaybe',
    'mapMaybeI',
    'mapResultErr',
    'mapResultErrI',
    'mapResultOk',
    'mapResultOkI',
    'mapTo',
    'mapToI',
    'mapWithIndex',
    'mapWithIndexI',
    'of',
    'pairwise',
    'pluck',
    'pluckI',
    'scan',
    'skip',
    'source',
    'throttleTime',
    'throttleTimeI',
    'unwrapMaybe',
    'unwrapMaybeI',
    'unwrapResultErr',
    'unwrapResultErrI',
    'unwrapResultOk',
    'unwrapResultOkI',
    'withInitialValue',
    'withLatestFrom',
    'withLatestFromI',
    'zip',
    'zipI',
  ],
  typeImportsList: [
    { name: 'InitializedObservable', params: ['A'] },
    { name: 'Observable', params: ['A'] },
    { name: 'Subscription', params: [] },
  ],
});
