import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { format } from 'prettier';
import { glob, Result } from 'ts-repo-utils';
import {
  extractTypeExports,
  type NamespaceExport,
  type TypeExport,
} from './extract-type-exports.mjs';

/**
 * Regenerates `src/global.mts`, which re-declares every named
 * ts-type-forge type as a global so consumers can opt-in to ambient
 * access via `/// <reference types="ts-type-forge/global" />`.
 *
 * Importing the package by name keeps named-only access without
 * polluting the global namespace.
 */
export const genGlobal = async (
  srcDir: string,
  globalFilePath: string,
): Promise<void> => {
  console.log(`Searching for .mts files in ${srcDir}...`);

  const filesResult = await glob(`${srcDir}/**/*.mts`);

  if (Result.isErr(filesResult)) {
    console.error(filesResult.value);

    return;
  }

  // FIXME: remove this cast
  const files: readonly string[] = filesResult.value;

  const moduleFiles = files
    .filter((p) => p !== globalFilePath)
    .filter((p) => path.basename(p) !== 'index.mts')
    .filter((p) => !p.endsWith('.test.mts'))
    .toSorted();

  const mut_allTypes: TypeExport[] = [];

  const mut_allNamespaces: NamespaceExport[] = [];

  for (const filePath of moduleFiles) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    const content = await fs.readFile(filePath, 'utf8');

    const { types, namespaces } = extractTypeExports(content);

    for (const e of types) mut_allTypes.push(e);

    for (const ns of namespaces) mut_allNamespaces.push(ns);
  }

  const mut_lines: string[] = [
    '/* eslint-disable @stylistic/padding-line-between-statements */',
    '// AUTO-GENERATED. DO NOT EDIT.',
    '// Regenerated by `pnpm run build` (genGlobal step).',
    '//',
    '// Re-declares every named ts-type-forge type as a global so consumers',
    '// can opt-in to ambient access via',
    '// `/// <reference types="ts-type-forge/global" />`.',
    "// Importing the package by name (`import { X } from 'ts-type-forge'`)",
    '// keeps named-only access without polluting the global namespace.',
    '',
    "import type * as _TSTypeForge from './index.mjs';",
    '',
    'declare global {',
  ];

  const typesForGlobal = mut_allTypes.filter((e) => !isInternalName(e.name));

  for (const e of typesForGlobal) {
    mut_lines.push(
      `  type ${e.name}${qualifyInternalRefs(e.generic)} = _TSTypeForge.${e.name}${e.argList};`,
    );
  }

  for (const ns of mut_allNamespaces) {
    mut_lines.push(`  namespace ${ns.name} {`);

    for (const e of ns.types) {
      mut_lines.push(
        `    export type ${e.name}${qualifyInternalRefs(e.generic)} = _TSTypeForge.${ns.name}.${e.name}${e.argList};`,
      );
    }

    mut_lines.push('  }');
  }

  mut_lines.push('}', '');

  const totalAliases =
    typesForGlobal.length +
    mut_allNamespaces.reduce((sum, ns) => sum + ns.types.length, 0);

  const formatted = await format(mut_lines.join('\n'), {
    parser: 'typescript',
    singleQuote: true,
    trailingComma: 'all',
  });

  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    await fs.writeFile(globalFilePath, formatted, 'utf8');

    console.log(
      `Successfully generated ${globalFilePath} with ${totalAliases} global type aliases (${mut_allNamespaces.length} namespaces).`,
    );
  } catch (error) {
    console.error(`Error writing to ${globalFilePath}:`, error);
  }
};

/**
 * `TSTypeForgeInternals_`-prefixed types are part of the named-import
 * surface but should not pollute the ambient declarations. They stay
 * reachable as `import { TSTypeForgeInternals_X } from 'ts-type-forge'`.
 */
const isInternalName = (name: string): boolean =>
  name.startsWith('TSTypeForgeInternals_');

/** Qualifies bare references to skipped internal types so the surviving
 * default-param values still resolve under `declare global`. */
const qualifyInternalRefs = (signature: string): string =>
  signature.replaceAll(
    /(?<![\w.])(TSTypeForgeInternals_\w*)/gu,
    '_TSTypeForge.$1',
  );
