// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IdFn from './IdFn.res.mjs';

function ifThen(antecedent, consequent) {
  if (antecedent) {
    return consequent;
  } else {
    return true;
  }
}

console.log(IdFn.idfn(true));

export { ifThen };
/*  Not a pure module */
