import { type Tile, type TileName } from '../types';

export const tileDef = {
  Manzu1: {
    id: 'Manzu1',
    no: 0,
    displayName: '一萬',
    MPSString: '1',
    TenhoMPSString: '1',
    TsumoProbString: '1m',
    order: 0,
    priority: 1,
  },
  Manzu2: {
    id: 'Manzu2',
    no: 1,
    displayName: '二萬',
    MPSString: '2',
    TenhoMPSString: '2',
    TsumoProbString: '2m',
    order: 1,
    priority: 2,
  },
  Manzu3: {
    id: 'Manzu3',
    no: 2,
    displayName: '三萬',
    MPSString: '3',
    TenhoMPSString: '3',
    TsumoProbString: '3m',
    order: 2,
    priority: 3,
  },
  Manzu4: {
    id: 'Manzu4',
    no: 3,
    displayName: '四萬',
    MPSString: '4',
    TenhoMPSString: '4',
    TsumoProbString: '4m',
    order: 3,
    priority: 4,
  },
  Manzu5: {
    id: 'Manzu5',
    no: 4,
    displayName: '五萬',
    MPSString: '5',
    TenhoMPSString: '5',
    TsumoProbString: '5m',
    order: 4,
    priority: 5,
  },
  Manzu6: {
    id: 'Manzu6',
    no: 5,
    displayName: '六萬',
    MPSString: '6',
    TenhoMPSString: '6',
    TsumoProbString: '6m',
    order: 5,
    priority: 4,
  },
  Manzu7: {
    id: 'Manzu7',
    no: 6,
    displayName: '七萬',
    MPSString: '7',
    TenhoMPSString: '7',
    TsumoProbString: '7m',
    order: 6,
    priority: 3,
  },
  Manzu8: {
    id: 'Manzu8',
    no: 7,
    displayName: '八萬',
    MPSString: '8',
    TenhoMPSString: '8',
    TsumoProbString: '8m',
    order: 7,
    priority: 2,
  },
  Manzu9: {
    id: 'Manzu9',
    no: 8,
    displayName: '九萬',
    MPSString: '9',
    TenhoMPSString: '9',
    TsumoProbString: '9m',
    order: 8,
    priority: 1,
  },
  Pinzu1: {
    id: 'Pinzu1',
    no: 9,
    displayName: '一筒',
    MPSString: '1',
    TenhoMPSString: '1',
    TsumoProbString: '1p',
    order: 9,
    priority: 1,
  },
  Pinzu2: {
    id: 'Pinzu2',
    no: 10,
    displayName: '二筒',
    MPSString: '2',
    TenhoMPSString: '2',
    TsumoProbString: '2p',
    order: 10,
    priority: 2,
  },
  Pinzu3: {
    id: 'Pinzu3',
    no: 11,
    displayName: '三筒',
    MPSString: '3',
    TenhoMPSString: '3',
    TsumoProbString: '3p',
    order: 11,
    priority: 3,
  },
  Pinzu4: {
    id: 'Pinzu4',
    no: 12,
    displayName: '四筒',
    MPSString: '4',
    TenhoMPSString: '4',
    TsumoProbString: '4p',
    order: 12,
    priority: 4,
  },
  Pinzu5: {
    id: 'Pinzu5',
    no: 13,
    displayName: '五筒',
    MPSString: '5',
    TenhoMPSString: '5',
    TsumoProbString: '5p',
    order: 13,
    priority: 5,
  },
  Pinzu6: {
    id: 'Pinzu6',
    no: 14,
    displayName: '六筒',
    MPSString: '6',
    TenhoMPSString: '6',
    TsumoProbString: '6p',
    order: 14,
    priority: 4,
  },
  Pinzu7: {
    id: 'Pinzu7',
    no: 15,
    displayName: '七筒',
    MPSString: '7',
    TenhoMPSString: '7',
    TsumoProbString: '7p',
    order: 15,
    priority: 3,
  },
  Pinzu8: {
    id: 'Pinzu8',
    no: 16,
    displayName: '八筒',
    MPSString: '8',
    TenhoMPSString: '8',
    TsumoProbString: '8p',
    order: 16,
    priority: 2,
  },
  Pinzu9: {
    id: 'Pinzu9',
    no: 17,
    displayName: '九筒',
    MPSString: '9',
    TenhoMPSString: '9',
    TsumoProbString: '9p',
    order: 17,
    priority: 1,
  },
  Sozu1: {
    id: 'Sozu1',
    no: 18,
    displayName: '一索',
    MPSString: '1',
    TenhoMPSString: '1',
    TsumoProbString: '1s',
    order: 18,
    priority: 1,
  },
  Sozu2: {
    id: 'Sozu2',
    no: 19,
    displayName: '二索',
    MPSString: '2',
    TenhoMPSString: '2',
    TsumoProbString: '2s',
    order: 19,
    priority: 2,
  },
  Sozu3: {
    id: 'Sozu3',
    no: 20,
    displayName: '三索',
    MPSString: '3',
    TenhoMPSString: '3',
    TsumoProbString: '3s',
    order: 20,
    priority: 3,
  },
  Sozu4: {
    id: 'Sozu4',
    no: 21,
    displayName: '四索',
    MPSString: '4',
    TenhoMPSString: '4',
    TsumoProbString: '4s',
    order: 21,
    priority: 4,
  },
  Sozu5: {
    id: 'Sozu5',
    no: 22,
    displayName: '五索',
    MPSString: '5',
    TenhoMPSString: '5',
    TsumoProbString: '5s',
    order: 22,
    priority: 5,
  },
  Sozu6: {
    id: 'Sozu6',
    no: 23,
    displayName: '六索',
    MPSString: '6',
    TenhoMPSString: '6',
    TsumoProbString: '6s',
    order: 23,
    priority: 4,
  },
  Sozu7: {
    id: 'Sozu7',
    no: 24,
    displayName: '七索',
    MPSString: '7',
    TenhoMPSString: '7',
    TsumoProbString: '7s',
    order: 24,
    priority: 3,
  },
  Sozu8: {
    id: 'Sozu8',
    no: 25,
    displayName: '八索',
    MPSString: '8',
    TenhoMPSString: '8',
    TsumoProbString: '8s',
    order: 25,
    priority: 2,
  },
  Sozu9: {
    id: 'Sozu9',
    no: 26,
    displayName: '九索',
    MPSString: '9',
    TenhoMPSString: '9',
    TsumoProbString: '9s',
    order: 26,
    priority: 1,
  },
  Ton: {
    id: 'Ton',
    no: 27,
    displayName: '東',
    MPSString: '東',
    TenhoMPSString: '1',
    TsumoProbString: '東',
    order: 27,
    priority: 1,
  },
  Nan: {
    id: 'Nan',
    no: 28,
    displayName: '南',
    MPSString: '南',
    TenhoMPSString: '2',
    TsumoProbString: '南',
    order: 28,
    priority: 1,
  },
  Sha: {
    id: 'Sha',
    no: 29,
    displayName: '西',
    MPSString: '西',
    TenhoMPSString: '3',
    TsumoProbString: '西',
    order: 29,
    priority: 1,
  },
  Pei: {
    id: 'Pei',
    no: 30,
    displayName: '北',
    MPSString: '北',
    TenhoMPSString: '4',
    TsumoProbString: '北',
    order: 30,
    priority: 1,
  },
  Haku: {
    id: 'Haku',
    no: 31,
    displayName: '白',
    MPSString: '白',
    TenhoMPSString: '5',
    TsumoProbString: '白',
    order: 31,
    priority: 1,
  },
  Hatsu: {
    id: 'Hatsu',
    no: 32,
    displayName: '發',
    MPSString: '發',
    TenhoMPSString: '6',
    TsumoProbString: '發',
    order: 32,
    priority: 1,
  },
  Chun: {
    id: 'Chun',
    no: 33,
    displayName: '中',
    MPSString: '中',
    TenhoMPSString: '7',
    TsumoProbString: '中',
    order: 33,
    priority: 1,
  },
  AkaManzu5: {
    id: 'AkaManzu5',
    no: 34,
    displayName: '赤五萬',
    MPSString: 'r5',
    TenhoMPSString: '0',
    TsumoProbString: 'r5m',
    order: 4,
    priority: 5,
  },
  AkaPinzu5: {
    id: 'AkaPinzu5',
    no: 35,
    displayName: '赤五筒',
    MPSString: 'r5',
    TenhoMPSString: '0',
    TsumoProbString: 'r5p',
    order: 13,
    priority: 5,
  },
  AkaSozu5: {
    id: 'AkaSozu5',
    no: 36,
    displayName: '赤五索',
    MPSString: 'r5',
    TenhoMPSString: '0',
    TsumoProbString: 'r5s',
    order: 22,
    priority: 5,
  },
} as const satisfies Record<TileName, Tile>;

export const ManzuTiles = {
  1: tileDef.Manzu1,
  2: tileDef.Manzu2,
  3: tileDef.Manzu3,
  4: tileDef.Manzu4,
  5: tileDef.Manzu5,
  6: tileDef.Manzu6,
  7: tileDef.Manzu7,
  8: tileDef.Manzu8,
  9: tileDef.Manzu9,
} as const;

export const PinzuTiles = {
  1: tileDef.Pinzu1,
  2: tileDef.Pinzu2,
  3: tileDef.Pinzu3,
  4: tileDef.Pinzu4,
  5: tileDef.Pinzu5,
  6: tileDef.Pinzu6,
  7: tileDef.Pinzu7,
  8: tileDef.Pinzu8,
  9: tileDef.Pinzu9,
} as const;

export const SozuTiles = {
  1: tileDef.Sozu1,
  2: tileDef.Sozu2,
  3: tileDef.Sozu3,
  4: tileDef.Sozu4,
  5: tileDef.Sozu5,
  6: tileDef.Sozu6,
  7: tileDef.Sozu7,
  8: tileDef.Sozu8,
  9: tileDef.Sozu9,
} as const;

export const JihaiTiles = {
  Ton: tileDef.Ton,
  Nan: tileDef.Nan,
  Sha: tileDef.Sha,
  Pei: tileDef.Pei,
  Haku: tileDef.Haku,
  Hatsu: tileDef.Hatsu,
  Chun: tileDef.Chun,
} as const;
