/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type Linter } from 'eslint';
import { type ReadonlyRecord, type TypeEq } from 'ts-type-forge';
import { type tsFortressRules } from './rules/index.mjs';

/**
 * @description Normalize a length-constrained ts-fortress array combinator whose bounds are degenerate (e.g. `minLengthArray(1, x)`, `boundedLengthTuple(n, n, x)`) to the combinator that names that constraint directly.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferCanonicalLengthConstrainedType {
  export type RuleEntry = Linter.StringSeverity;
}

export type EslintTsFortressRules = Readonly<{
  'ts-fortress/prefer-canonical-length-constrained-type': PreferCanonicalLengthConstrainedType.RuleEntry;
}>;

export type EslintTsFortressRulesOption = ReadonlyRecord<never, never>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
type AssertTrue<B extends true> = B;

export type RuleNamesAreInSync = AssertTrue<
  TypeEq<
    keyof EslintTsFortressRules,
    `ts-fortress/${keyof typeof tsFortressRules}`
  >
>;
