/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type Linter } from 'eslint';
import { type TypeEq } from 'ts-type-forge';
import { type tsFortressRules } from './rules/index.mjs';

/**
 * @description Replace `minLengthArray(1, ...)` with `nonEmptyArray(...)` from ts-fortress.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferNonEmptyArray {
  export type RuleEntry = Linter.StringSeverity;
}

export type EslintTsFortressRules = Readonly<{
  'ts-fortress/prefer-non-empty-array': PreferNonEmptyArray.RuleEntry;
}>;

export type EslintTsFortressRulesOption = Readonly<Record<never, never>>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
type AssertTrue<B extends true> = B;

export type RuleNamesAreInSync = AssertTrue<
  TypeEq<
    keyof EslintTsFortressRules,
    `ts-fortress/${keyof typeof tsFortressRules}`
  >
>;
