/* cSpell:disable */

// This file is auto-generated by `pnpm run gen:rule-types`
// (`scripts/cmd/gen-rule-types.mts`). Do not edit it manually.

import { type Linter } from 'eslint';
import { expectType } from 'ts-std-forge';
import { type tsStdForgeRules } from './rules/index.mjs';

/**
 * @description Replace `typeof u === "object" && u !== null` with `isNonNullObject(u)` from ts-std-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferIsNonNullObject {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `Object.hasOwn(obj, key)` or `key in obj` with `isRecord(obj) && hasKey(obj, key)` from ts-std-forge
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferIsRecordAndHasKey {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `Array.isArray` with `SafeArray.isArray` from ts-std-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferSafeArrayIsArray {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace an emptiness check on an array (`xs.length === 0`, `xs.length > 0`, `xs.length >= 1`, `xs.length !== 0`) with `SafeArray.isEmpty(xs)` / `SafeArray.isNonEmpty(xs)` from ts-std-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferSafeArrayLengthGuard {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `parseFloat(x)`, `Number.parseFloat(x)`, or `Number(x)` (when x is a string) with `Result.unwrapOkOr(SafeNumber.parse(x), Number.NaN)` from ts-std-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferSafeNumberParse {
  export type RuleEntry = Linter.StringSeverity;
}

/**
 * @description Replace `parseInt(x)` or `Number.parseInt(x, 10)` with `Result.unwrapOkOr(SafeNumber.parseInteger(x), Number.NaN)` from ts-std-forge.
 *
 *  ```md
 *  | key        | value      |
 *  | :--------- | :--------- |
 *  | type       | suggestion |
 *  | deprecated | false      |
 *  | fixable    | code       |
 *  ```
 */
namespace PreferSafeNumberParseInteger {
  export type RuleEntry = Linter.StringSeverity;
}

export type EslintTsStdForgeRules = Readonly<{
  'ts-std-forge/prefer-is-non-null-object': PreferIsNonNullObject.RuleEntry;
  'ts-std-forge/prefer-is-record-and-has-key': PreferIsRecordAndHasKey.RuleEntry;
  'ts-std-forge/prefer-safe-array-is-array': PreferSafeArrayIsArray.RuleEntry;
  'ts-std-forge/prefer-safe-array-length-guard': PreferSafeArrayLengthGuard.RuleEntry;
  'ts-std-forge/prefer-safe-number-parse': PreferSafeNumberParse.RuleEntry;
  'ts-std-forge/prefer-safe-number-parse-integer': PreferSafeNumberParseInteger.RuleEntry;
}>;

export type EslintTsStdForgeRulesOption = Readonly<{}>;

// If this assertion fails to type-check, this generated file has drifted from
// the actual plugin rules — re-run `pnpm run gen:rule-types`.
expectType<
  keyof EslintTsStdForgeRules,
  `ts-std-forge/${keyof typeof tsStdForgeRules}`
>('=');
