# This is a basic workflow to help you get started with Actions

name: Deploy my-portfolio-app-preact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [develop]
    paths:
      - .github/workflows/deploy_portfolio_app.yml
      - config/tsconfig/**
      - yarn.lock
      - packages/utils/**
      - packages/apps/my-portfolio-app-preact/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildAndDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # Set up GitHub Actions caching for Wireit.
      # - uses: google/wireit@setup-github-actions-caching/v1.0.2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: build dependencies
        run: yarn zz:wsrun-stages --recursive -p @noshiro/my-portfolio-app-preact -c build

      - name: lint
        run: yarn workspace @noshiro/my-portfolio-app-preact lint

      - name: test
        run: yarn workspace @noshiro/my-portfolio-app-preact test

      - name: deploy
        run: yarn workspace @noshiro/my-portfolio-app-preact fb:deploy
        env:
          PROJECT_ID: release
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
