# This is a basic workflow to help you get started with Actions

name: E2E test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
      - 'archive/**'
      - 'deploy/**'
    paths-ignore:
      - '.gitignore'
      - '.cspell.json'
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.txt'
      - 'articles/**'
      - 'books/**'
      - 'docs/**'
      - 'experimental/**'
      - 'packages/slides/**'
      - 'packages/others/**'
      - 'packages/tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-run:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app_name:
          - algo-app
          - annotation-tool
          - blueprintjs-playground
          - blueprintjs-playground-styled
          - cant-stop-probability-app
          - catan-dice-app
          - color-demo-app
          - housing-loan-calculator-app
          - lambda-calculus-interpreter-preact
          - lambda-calculus-interpreter-react
          - my-portfolio-app-preact
          - mahjong-calculator-app
          - slack-app
          - template-preact-app-vite
          - template-react-app-vite

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.2
        id: setup_node_id
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Build dependencies
        run: yarn zz:wsrun-stages --recursive -p @noshiro/${{ matrix.app_name }} -c build

      - name: Run Playwright tests
        run: yarn workspace @noshiro/${{ matrix.app_name }} e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/apps/{{ matrix.app_name }}/playwright-report/
          retention-days: 30

  e2e-event-schedule-app:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setting-up JAVA
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - uses: actions/setup-node@v4.0.2
        id: setup_node_id
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Build dependencies
        run: yarn zz:wsrun-stages --recursive -p @noshiro/event-schedule-app -c build

      - name: Build functions
        run: yarn workspace @noshiro/event-schedule-app-functions build

      # - name: create runtimeconfig
      #   run: yarn workspace @noshiro/event-schedule-app z:setup:fb:emulators:gen-dummy-runtimeconfig

      - name: Run Playwright tests
        run: yarn workspace @noshiro/event-schedule-app e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/apps/event-schedule-app/playwright-report/
          retention-days: 30
