# This is a basic workflow to help you get started with Actions

name: E2E test for event-schedule-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:
      - 'dev'
      - 'develop'
      - 'archive/**'
    paths-ignore:
      - 'docs/**'
      - 'experimental/**'
      - '**.md'
      - '**.txt'
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting-up JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # - name: Save build folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: packages/apps/event-schedule-app

      # Set up GitHub Actions caching for Wireit.
      # - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: ws:setup
        run: yarn ws:setup

      - name: create runtimeconfig
        run: yarn workspace @noshiro/event-schedule-app fb:emulators:gen-dummy-runtimeconfig

      # - name: Cypress install
      #   uses: cypress-io/github-action@v2
      #   with:
      #     # Disable running of tests within install job
      #     runTests: false
      #     install: false
      #     working-directory: packages/apps/event-schedule-app
      #     build: yarn build

      # - name: Download the build folders
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build
      #     path: packages/apps/event-schedule-app

      # - name: Start App
      #   run: yarn workspace @noshiro/event-schedule-app start &

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v4
        with:
          # group: 'UI - Chrome'
          browser: chrome
          install: false
          working-directory: packages/apps/event-schedule-app
          spec: cypress/e2e/**/*.js
          start: |
            yarn start:emulators
            yarn start:dev-server
          # wait-on: 'http://localhost:8080, http://localhost:8081, http://localhost:5001'
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          headless: true
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Cypress run on Firefox
      #   uses: cypress-io/github-action@v2
      #   with:
      #     # group: 'UI - Firefox'
      #     browser: firefox
      #     install: false
      #     working-directory: packages/apps/event-schedule-app
      #     # spec: cypress/e2e/*
      #     # build: yarn build
      #     start: yarn start:dev-server, yarn start:emulators
      #     wait-on: 'http://localhost:8080'
      #     wait-on-timeout: 120
      #     record: true
      #     parallel: true
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     # Recommended: pass the GitHub token lets this action correctly
      #     # determine the unique run id necessary to re-run the checks
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
