# This is a basic workflow to help you get started with Actions

name: fmt-check

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
      - 'archive/**'
      - 'deploy/**'
      - 'create-codemod-lib'
    paths-ignore:
      - '.gitignore'
      - '**.png'
      - '**.jpg'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fmt-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        id: setup_node_id
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # - run: echo '${{ toJSON(steps.setup_node_id.outputs) }}'
      # - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
      - name: Install dependencies
        run: yarn

      - name: Setup
        run: yarn fmt

      - name: Check if there is no file diff
        run: yarn zz:check:no-diff
