# This is a basic workflow to help you get started with Actions

name: lint-test-type-check

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
      - 'archive/**'
      - 'deploy/**'
    paths-ignore:
      - '.gitignore'
      - '.cspell.json'
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.txt'
      - 'articles/**'
      - 'books/**'
      - 'docs/**'
      - 'experimental/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-test-type-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: true
      matrix:
        command:
          - fmt:all
          - ws:gi
          - ws:type-check
          - ws:test
          - ws:build:non-utils
          - ws:lint:fix
          - workspace @noshiro/syncflow test:stream

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.2
        id: setup_node_id
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1.0.2

      # - run: echo '${{ toJSON(steps.setup_node_id.outputs) }}'
      # - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
      - name: Install dependencies
        run: yarn

      - name: Check if there is no file diff
        run: yarn zz:cmd:check:no-diff

      - name: Run "${{ matrix.command }}"
        run: yarn ${{ matrix.command }}

      - if: ${{ !contains(fromJSON('["ws:type-check", "ws:test", "workspace @noshiro/syncflow test:stream"]'), matrix.command) }}
        name: Check if there is no file diff
        run: yarn zz:cmd:check:no-diff
