# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'develop'
      - 'archive/**'
    paths-ignore:
      - 'docs/**'
      - 'experimental/**'
      - '**.md'
      - '**.txt'
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install dependencies
        run: yarn --frozen-lockfile

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn ws:build
      - run: yarn zz:cmd:check:no-diff

  gi:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn ws:gi
      - run: yarn zz:cmd:check:no-diff

  type-check-root:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - run: yarn type-check:root

  type-check:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - run: yarn ws:type-check

  test:
    needs: [setup, build, type-check-root, type-check]
    runs-on: ubuntu-latest
    steps:
      - run: yarn ws:test

  format:
    needs: [setup, build, type-check-root, type-check]
    runs-on: ubuntu-latest
    steps:
      - run: yarn fmt:all
      - run: yarn zz:cmd:check:no-diff

  eslint-fix:
    needs: [setup, build, type-check-root, type-check]
    runs-on: ubuntu-latest
    steps:
      - run: yarn ws:lint:fix
      - run: yarn zz:cmd:check:no-diff
