# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'develop'
      - 'archive/**'
    paths-ignore:
      - 'docs/**'
      - 'experimental/**'
      - '**.md'
      - '**.txt'
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      # - run: echo '${{ toJSON(steps.setup_node_id.outputs) }}'
      # - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: gi
        run: |
          yarn ws:gi
          yarn zz:cmd:check:no-diff

      - name: build
        run: |
          yarn ws:build
          yarn zz:cmd:check:no-diff

      - name: type-check:root
        run: yarn type-check:root

      - name: ws:type-check
        run: yarn ws:type-check

      - name: ws:test
        run: yarn ws:test

      - name: fmt:all
        run: |
          yarn fmt:all
          yarn zz:cmd:check:no-diff

      - name: ws:lint:fix
        run: |
          yarn ws:lint:fix
          yarn zz:cmd:check:no-diff
